Cargo.toml
src/cli/mod.rs
src/error.rs
src/main.rs

This PR is the start of the series to introduce Command Line handling. The overall idea is, when adding a new command, one just needs to implement the core execution logic. The parsing of command line args, dispatching and response display are already taken care of. One just needs to register the handler to a registry. 
This PR introduces the trait that represents the abstraction of a command line handler.  To implement a new command line operation, implement this trait.
Example code can be found in #12.

Add cli command handler interface

---

src/jsonrpc/mod.rs
src/jsonrpc/tests.rs

This PR fixes a bug in checking the ID and version fields in the `request` method of `JsonRpcClientImpl`. It also fixes some related tests and removes the `ignore` directive on the less flaky tests.

Fixes error checking in JsonRpcClient requests and tests

---

Cargo.toml
ipld/resolver/Cargo.toml
ipld/resolver/src/lib.rs
rust-toolchain.toml

Related to #17 
The PR creates an `ipld/resolver` crate and puts it in the workspace. 
Also added a `rust-toolchain.toml` file with the same content as `ref-fvm` - without it I wasn't able to build the actor dependencies due to wasm stuff. Nightly and the wasm-target seems to fix the issue, and at least we'd all be on the same config.

IPC-17: Create ipld/resolver crate

---

src/lotus/client.rs
src/lotus/message.rs
src/lotus/mod.rs
src/lotus/tests.rs

The first of a series of changes to add new JSON-RPC method calls to the `LotusClient` necessary for checkpointing implementation. This one adds the `ChainHead` call. The deserialization is done into a simplified data structure that does not decode the entire response. In particular, we leave out the `blocks` field due to its complexity which is unnecessary for our purposes.

Add a method to LotusClient for retrieving the chain head

---

Cargo.lock
Cargo.toml
ipld/resolver/Cargo.toml
ipld/resolver/src/behaviour/discovery.rs
ipld/resolver/src/behaviour/membership.rs
ipld/resolver/src/behaviour/mod.rs
ipld/resolver/src/hash.rs
ipld/resolver/src/lib.rs
ipld/resolver/src/provider_cache.rs

Closes #35 
Follow up to #44, this PR adds configuration to the `membership` module and refactors the `discovery` module to get rid of the `ConfigBuilder` and extract common configuration fields into a `NetworkConfig`. 
It also adds `pin_subnet` methods to the `Behaviour` and the `SubnetProviderCache`, which can be used to let the module know about the existence of some known subnet IDs that it should never prune from the cache. This is to prevent attackers trying to throw tons of random subnets at us and prevent us from overcoming their numbers and learn who to resolve the content of real subnets from.
The reason I removed the builder is because I found having to repeat fields 3 times (`Config`, `ConfigBuilder` and `Behaviour`) annoying, and in the end it still wasn't enough to nicely …

IPC-35: Config

---

Cargo.lock
Cargo.toml
ipld/resolver/Cargo.toml
ipld/resolver/src/behaviour/content.rs
ipld/resolver/src/behaviour/mod.rs
ipld/resolver/src/lib.rs
ipld/resolver/src/missing_blocks.rs

Closes #36 
The PR adds a `content::Behaviour` that wraps `Bitswap` and adds the `resolve` method to recursively retrieve a tree of CIDs.
This is a small PR, as it turns out there's not much to be done over Bitswap, it's mostly just comments and calling the right method the right way for what we're trying to achieve. All the book-keeping will have to happen further up in the #37 
A potential extension could be to pass not just a list of peers, but a list of connected peers and a list of known, but unconnected peers as well, and then make two queries: try with the connected ones first, then the unconnected, or use up to N combined in the first try, etc. This can also be done in the service, though, as separate queries, but we could add a separate `QueryId` to this behaviour and manage it …

IPC-36: Content behaviour

---

Cargo.lock
ipld/resolver/Cargo.toml
ipld/resolver/src/behaviour/content.rs
ipld/resolver/src/behaviour/discovery.rs
ipld/resolver/src/behaviour/membership.rs
ipld/resolver/src/behaviour/mod.rs
ipld/resolver/src/lib.rs
ipld/resolver/src/provider_record.rs
ipld/resolver/src/service.rs

Closes #37 
The PR creates a `Service` and `Client` to act as the public interface of content resolution. 
The `Service` is what users of the library have to instantiate, it creates all the behaviours created in #34 , #35 and #36 , along with a `Client`, which can be used to send requests/commands to it over a channel. The `Client` can be cloned, so that a separate instance can be given to any component that needs to talk to the `Service`. 
Instead of an request/response queue as in Forest, the `Client` hides the query behind an async `resolve` method. The caller needs to tell which CID they want to resolve and from which subnet. The `Service` returns an error immediately if there are no peers known in that subnet.
The other two methods at the moment are to set a list of subnets the agent …

IPC-37: Resolver Service and Client

---

ipld/resolver/src/behaviour/discovery.rs

Closes #58 
The PR disables the storing of Kademlia records in the store and warns if any peers sends us such requests.

IPC-58: Disable Kademlia storage inserts

---

src/config/mod.rs
src/lotus/client.rs
src/lotus/message/ipc.rs
src/lotus/mod.rs

The two method calls are `ipc_read_gateway_state` and `ipc_read_subnet_actor_state`. This PR is part of a stack where the following one (#61) adds the checkpointing logic.

Adds JSON-RPC method calls to read the state of the IPC actors and a convenience method to construct a LotusJsonRPCClient from a subnet config.

---

Cargo.lock
Cargo.toml
src/cli/commands/daemon.rs
src/config/mod.rs
src/config/reload.rs
src/config/tests.rs
src/server/handlers/config.rs
src/server/handlers/mod.rs
src/server/jsonrpc.rs

Update config while the json rpc server is running.
`ReloadableConfig` exposes the latest config through `get_config` method. Use this you will always the latest config. At the same time, it also exposes `new_subscriber`. If caller needs to be notified when config has updated, just make a new subscription. Once received a notification, then just read the config again to obtain the latest config.
See `reload_works` test case for sample usage.

Reload config

---

ipld/resolver/Cargo.toml
ipld/resolver/src/service.rs
ipld/resolver/tests/smoke.rs

Closes #68 
Changes the strategy for how many peers to contact in bitswap, from "first to all connected, then if failed then all other known providers" to "the first N of connected and known, then the next N, and so on". Also shuffles the peers so we don't always go to the same one.

IPC-68: Max peers per query

---

ipld/resolver/src/behaviour/discovery.rs
ipld/resolver/src/service.rs

Closes #70 
Changes the `Discovery` behaviour to buffer `Identify::Info` records while the Kademlia bootstrapping is ongoing.

IPC-70: Bootstrap Eclipse attack protection 

---

ipld/resolver/src/behaviour/membership.rs
ipld/resolver/src/provider_cache.rs
ipld/resolver/tests/smoke.rs

Closes #67 
So far we published provider records whenever they changed, and independently at regular intervals. This presented a trade-off in that new joiners would have to wait until they get a full picture of subnet providers. In the #64 I had to set the publish interval low, because currently records are only accepted once the listening address of the other party is known, and it takes time for `Identify` and `Kademlia` to work. 
The PR changes this so that records are also published at the following triggers:
* A peer subscribes to the membership topic - this indicates we just established a Gossipsub connection with them and they might be interested to know about our subnets
* A peer became routable - this indicates that we just received their address through Identify or Kademlia; …

IPC-67: Gossip to new joiners

---

src/jsonrpc/tests.rs
src/lotus/tests.rs

Disable 3 flaky tests:
- test_request_with_params
- state_network_name
- state_actor_manifest_cid
These 3 tests are just querying the public lotus node to check the lotus response format.  They worked fine previously, but recently, they return `Method not supported` error unpredictably. 
The point for these tests are just checking the response format, which we have already confirmed. Disable the run for now as they are breaking the CICD.

Disable 3 flaky tests

---

Cargo.lock
Cargo.toml
ipld/resolver/Cargo.toml
ipld/resolver/src/behaviour/content.rs
ipld/resolver/src/behaviour/discovery.rs
ipld/resolver/src/behaviour/membership.rs
ipld/resolver/src/lib.rs
ipld/resolver/src/provider_cache.rs
ipld/resolver/src/service.rs
ipld/resolver/src/stats.rs

Closes #65 
The PR adds a bunch of Prometheus metrics to the library, and a `Service::register_metrics` method, similar to the one `Bitswap` has.

IPC-65: Metrics

---

Cargo.lock
ipld/resolver/Cargo.toml
ipld/resolver/src/behaviour/content.rs
ipld/resolver/src/behaviour/mod.rs
ipld/resolver/src/lib.rs
ipld/resolver/src/limiter.rs
ipld/resolver/src/service.rs
ipld/resolver/src/stats.rs
ipld/resolver/tests/smoke.rs

Closes #86 
The PR uses the [gcra](https://crates.io/crates/gcra) library to rate limit the amount of data that can go to any individual `MultiAddress` via `Bitswap`. The `content::Config` gets two new fields, `rate_limit_bytes` and `rate_limit_period`, so that we can configure e.g. that any peer cannot download more than 10MB/hour from us. 
The `Client` has a new `update_rate_limit` method we can use to adjust this value on the fly, if we see that this is going to be too tight. The `gcra` library was picked because it allows passing in the limit with each request, unlike for example the [governor](https://crates.io/crates/governor). 
To make it work, I had to fork `libp2p-bitswap`, because normally it sends the response straight to the connection handler, which writes it to the socket. …

IPC-86: Rate limit

---

config/template.toml
src/config/deserialize.rs
src/config/server.rs
src/config/tests.rs
src/main.rs
src/server/jsonrpc.rs

Setting the network from env variable. This is because in the config, it's deserializing based on a network, if the network is not set, it will give an error.

set network

---

src/cli/commands/manager/create.rs
src/lotus/message/deserialize.rs
src/lotus/message/ipc.rs
src/lotus/message/tests.rs

Adds a set of fixes to make `list-subnets` actually work after the fixes in its Go counterpart.
@cryptoAtwill if there is no major comment, feel free to merge as soon as you approve to move fast :pray:

Fix serialization for list-subnets

---

src/cli/commands/daemon.rs
src/config/reload.rs
src/config/tests.rs
src/manager/checkpoint.rs
src/server/handlers/config.rs
src/server/handlers/mod.rs
src/server/jsonrpc.rs

This injects the ReloadableConfig as a constructor parameter into the JsonRPCServer as opposed to having the JsonRPCServer constructing it. The allows the ReloadableConfig to be resued by other components. In particular, it will allow the CheckpointSubsystem to use it.

Inject ReloadableConfig into JsonRPCServer

---

src/server/request.rs
src/server/response.rs

Fix the type of ID in our json_rpc requests and reponses to `u64` so it is consistent with other external libraries

make json_rpc type u64 to be consistent with other libs

---

src/jsonrpc/mod.rs

While testing I realized that if a subnet is not mining the cli requests from the agent gets stuck forever without any feedback to the user. This PR includes a default timeout to all json-rpc requests from the lotus client. We could make this configurable but I don't think there is a use case right now.
NOTE: When a message is published to the mempool a peer will try to republish it periodically until it is accepted unless we tell it otherwise, which means that even if we timeout a request those that involve message could still go through. This is something worth documenting so users are aware.

add timeout to improve cli ux

---

Cargo.lock
src/cli/commands/manager/mod.rs
src/cli/commands/manager/send_value.rs
src/cli/commands/mod.rs
src/config/server.rs
src/lotus/message/state.rs
src/manager/lotus.rs
src/manager/subnet.rs
src/server/handlers/manager/mod.rs
src/server/handlers/manager/send_value.rs
src/server/handlers/mod.rs

The same way that we provide methods to send value between addresses in different subnets, it is useful to provide a way through the agent to send tokens between addresses in the same subnet. When testing the agent, I realized this is a common operation, and after having configured the agent to operate with a specific subnet peer, is kind of an overhead to have to connect to the Lotus API of the corresponding peer, send the request, etc. This is even worse when the peer is run in docker. 
This PR:
- Includes a new method `send-value` that allows to send value between two addresses in the same subnet.
- Fixes a bug for which `state_wait_msg` failed when the return value is empty.

Send Value between addresses of the same subnet

---

src/lib.rs
src/main.rs
src/manager/checkpoint.rs

Wraps the bulk of the checkpoint logic in a `try` block and adds error context to the result of the block.

Add context to error propagation in manage_subnet

---

src/lotus/client.rs
src/lotus/json.rs
src/lotus/mod.rs

This PR adds a `ToJson` trait and implements it for `SubnetID`. This reduces a substantial amount of boilerplate code in the `LotusClient` implementation. It's a dependency for #140 and #141.

Adds ToJson trait to facilitate converstion of SubnetID to JSON

---

Cargo.lock
Cargo.toml

As we are making changes to IPC actors, we may introduce changes that are not backward compatible for the agent. To clearly tag the version of actors an IPC agent is compatible with, this PR introduces tagged version to the IPC actors dependency. 
In the future, we should use proper versions through a published crate instead of pointing to a tag in a repo, but for now, as the code is not yet stable and we expect changes quite often, it is more comfortable to publish always the same cargo version `v0.0.1` and use `tag` to determine the github `release` of the actors a version of the agent is compatible with.

use tag versioning for ipc-actors

---

src/lib.rs
src/lotus/client.rs
src/lotus/mod.rs
src/manager/lotus.rs
src/manager/subnet.rs
src/serialization/checkpoint.rs
src/serialization/mod.rs
src/server/handlers/manager/list_checkpoints.rs

For all checkpoint related interaction with lotus node, we will use direct bytes returned and actor's implementation of deserialization. Once this is tested, we shall remove the wrapper structs.
Also added the serialization to json for `ipc-agent` json rpc server. 
Once tested, we should consider moving `serialization` module to `ipc-actor` repo's `sdk` crate.

Update Checkpoint serialization/deserialization

---

README.md
docs/quickstart.md
docs/subnet.md
docs/troubleshooting.md
docs/usage.md

* Removes leading prompt from bash blocks
* Separates examples into console blocks
This was a bit rushed so some decisions may have been suboptimal given there are some edge cases.
For the now-separate examples, we should add the expected outcome -- which we have in some cases, not in others. But this should already improve quality of life for the reader, so I wouldn't block on re-executing things for output.

Improve formatting of commands and examples

---

src/cli/commands/crossmsg/fund.rs
src/cli/commands/crossmsg/release.rs
src/cli/commands/subnet/create.rs
src/cli/commands/subnet/join.rs
src/cli/commands/subnet/send_value.rs
src/server/handlers/manager/create.rs
src/server/handlers/manager/fund.rs
src/server/handlers/manager/join.rs
src/server/handlers/manager/release.rs
src/server/handlers/manager/send_value.rs
src/server/handlers/mod.rs
testing/e2e/src/lib.rs

This is a PR to address the issue #178. Uses `f64` over `u64` for amount in send value calls.

Replace u64 with f64 for FIL amount

---

.gitignore
scripts/install_infra.sh

This PR makes `infra_install.sh` work on MacOS.
Issue https://github.com/consensus-shipyard/ipc-agent/issues/183

Fix script for mac

---

src/jsonrpc/mod.rs

The 30s timeout we had wasn't enough to accommodate the delay of sending a transaction to calibration and mainnet.

increase timeout to support mainnet/calibration

---

Cargo.toml
identity/src/evm/mod.rs
identity/src/lib.rs
src/checkpoint/fevm_fvm/topdown.rs
src/manager/evm/manager.rs
src/server/handlers/config.rs
src/server/handlers/manager/create.rs
src/server/handlers/wallet/import.rs
testing/itest/src/infra/mod.rs
testing/itest/src/infra/subnet.rs
testing/itest/src/infra/util.rs

This PR contains some adhoc fixes after performing integration testing, key changes:
1. Update `itest` crate to accommodate evm keystore changes
2. Set default file name for evm keystore

Fix keystore after integration testing

---

README.md
docs/calibration-solidity.md
docs/evm-usage.md
docs/quickstart.md
docs/subnet.md
docs/usage.md

This PR adds a quickstart guide to deploy IPC solidity contracts to Calibration. Additionally, it updates the config and cross-net message primitives with all the changes to be included in the next release.

docs to deploy IPC Solidity in calibration

---

src/manager/evm/conversion.rs
src/manager/evm/manager.rs
src/manager/evm/mod.rs
src/server/handlers/manager/send_value.rs
src/server/handlers/wallet/balances.rs

This PR: 
- It implements `send_value` support for EVM-based subnets
- Moves a few function arounds to improve code organization

add send_value evm support

---

src/lotus/client.rs
src/manager/evm/manager.rs

The Lotus client is only used when the subnet is of type `fvm`. This is currently only supported in child subnets running an instant-finality consensus (Mir/Tendermint), so we can afford having 0 epoch of confidence in state wait. This reduces the latency when interacting with the subnet from the IPC agent. 
In the same line, the PR increases the default polling time of the ETH provider to fit the block times of our instant finality subnets.

remove confidence wait for StateWait in Lotus

---

src/checkpoint/mod.rs
src/manager/evm/manager.rs

This PR fixes a regression after increasing the polling time of the ETH provider for which subnet delays wherre accelerated but it was causing timeouts with slow networks like Calibration.

fix retries to support calibration

---

.github/workflows/branch-check.yaml

@adlrocha following slack discussion: this would allow us to retain main as the default while automatically redirecting in case some rattlebrain like me targets the wrong branch.

Add action to check and fix PR targets

---

docs/quickstart-calibration.md

This documentation update addresses the issues found with validators failing to sync due to lack of connectivity-
Once again, targetting `main` given current state of the docs.

Add quickstart step for peering

---

docs/quickstart-calibration.md
docs/quickstart-spacenet.md
scripts/install_infra.sh

The lotus repo was the outlier in that the unstable `dev` branch was default. This switches the docs and scripts to match making `main` (aliased `spacenet`) the default branch.

Adjust scripts/docs for lotus main as default

---

README.md
docs/quickstart-calibration.md
docs/troubleshooting.md
testing/e2e/template/eudico/genesis/README.md
testing/e2e/template/eudico/scripts/subnet-validator.sh

Updates docs to use calibration as default. Also replaces references to the `spacenet` branch of eudico with `main`.

Docs: Move to calibration as default

---

Cargo.lock
Cargo.toml
src/manager/evm/manager.rs

__Note: Do not merge yet, I want to thoroughly test before merging__
Fixes https://github.com/consensus-shipyard/ipc-agent/issues/276
`ethers` performs several Ethereum-specific assumptions to estimate the gas premium. When the premium is too low, it sets a default premium that corresponds to `3 nanoFiL`. The average premiums paid in Filecoin are lower than the ones in Filecoin, what led to `ethers` always setting the premium to the default value (quite high for the case of Filecoin). 
This PR addresses the issue by using a custom premium estimation based on the historical premium paid in the last few blocks. Unlike `ethers` we don't use a threshold trigger that sets the default premium. This gas estimation is used for every  `eth_call` from the agent.

IPC-287: Fix high premium in eth_call

---

src/checkpoint/mod.rs

Fixes #284 
Previously checkpoint look ahead is using a fix epoch number, the issue is when the checkpoint period is larger than the checkpoint look ahead, the checkpoint submission logic is not triggered.
```rust
while next_epoch < cut_off_epoch {
...
}
```
will be expanded to:
```rust
while (last_executed_epoch + period) < (SUBMISSION_LOOK_AHEAD_EPOCH + last_executed_epoch) {
...
}
```
which is:
```
while period < SUBMISSION_LOOK_AHEAD_EPOCH {
...
}
```
Fix checkpoint look ahead using multiple of checkpoint period will resolve the issue. 
```rust
let cut_off_epoch = std::cmp::min(
current_epoch,
SUBMISSION_LOOK_AHEAD_ROUNDS * period + last_executed_epoch,
);
```
Current `SUBMISSION_LOOK_AHEAD_ROUNDS` is set to 5, we can adjust this number in the future as we see more fit.

Fix checkpoint look ahead

---

.github/workflows/ci.yaml
.github/workflows/release-binaries.yaml

On release, builds and attaches binaries for linux x64 and darwin universal (arm+x64).
Also replaces deprecated action (see https://github.com/consensus-shipyard/fendermint/pull/188#discussion_r1295111695)
Closes #292

Add gh action to upload binaries on release

---

ipc/cli/src/commands/subnet/rpc.rs
ipc/provider/src/lib.rs
ipc/provider/src/manager/evm/manager.rs
ipc/provider/src/manager/fevm.rs
ipc/provider/src/manager/fvm/mod.rs
ipc/provider/src/manager/subnet.rs

This PR implements a `get_chain_id` convenient function to provider and exposes it in a cli command.

IPC-299: implement get-chain-id

---

ipc/cli/src/main.rs
ipc/identity/src/evm/persistent.rs
ipc/identity/src/lib.rs
ipc/provider/src/lib.rs
ipc/sdk/Cargo.toml
ipc/sdk/src/checkpoint.rs
ipc/sdk/src/lib.rs
ipc/sdk/src/runtime.rs
rust-toolchain.toml

Some minor code clean ups:
- Switching to stable rust and remove the above features:
- There is unused features: `try_block`, which we can remove. 
- Also there is `let_chain`, which we can easily bypass.
- Move all `fil_actor::Runtime` related to a separate module

Minor clean up

---

Cargo.lock
Cargo.toml
ipc/cli/Cargo.toml
ipc/cli/src/commands/subnet/create.rs
ipc/cli/src/commands/subnet/list_subnets.rs
ipc/cli/src/commands/wallet/balances.rs
ipc/cli/src/commands/wallet/export.rs
ipc/cli/src/commands/wallet/mod.rs
ipc/identity/Cargo.toml
ipc/provider/src/checkpoint.rs
ipc/provider/src/config/mod.rs
ipc/provider/src/lib.rs
ipc/provider/src/manager/evm/manager.rs
ipc/provider/src/manager/mod.rs
ipc/provider/src/manager/subnet.rs
ipc/sdk/src/checkpoint.rs
ipc/sdk/src/lib.rs
ipc/sdk/src/subnet.rs
ipc/sdk/src/validator.rs

Related to https://github.com/consensus-shipyard/fendermint/issues/306
Depends on https://github.com/consensus-shipyard/ipc-agent/pull/336
This PR introduces a new method in the provider to retrieve all the genesis information in the parent required to deterministically generate the genesis for a Fendermint child subnet.
It also introduces `min_cross_msg_fee` as an additional configuration parameter that users can set when they create their subnets and many other changes.

FM-306: add method in provider to get genesis info

---

README.md

Starting point for the rework of the whole documentation. It updates the README to remove any reference to the IPC agent so we can rename the repo to `ipc`.

Update README as a starting point for the doc update

---

docs/quickstart-calibration.md
ipc/cli/src/commands/crossmsg/release.rs
ipc/cli/src/commands/wallet/balances.rs
ipc/provider/src/config/mod.rs
ipc/provider/src/lib.rs
ipc/provider/src/manager/evm/manager.rs
ipc/provider/src/manager/subnet.rs

This PR includes several minor fixes.
- It adds the new default addresses for the IPC contracts when deployed in genesis by Fendermint in child subnets: https://github.com/consensus-shipyard/fendermint/pull/338
- It re-arranges the fields of the config in the template. 
- It fixes the `release` command so it passes the `fee` correctly.
- It updates the docs and adds additional logs.

FIX: release, default IPC addresses in child subnet, minor fixes

---

docs/quickstart-calibration.md
docs/usage.md
ipc/cli/src/commands/wallet/export.rs
scripts/install_infra.sh

Depends on https://github.com/consensus-shipyard/fendermint/pull/329
Closes #351 #354
- Updates the infra scripts to use the latest version from https://github.com/consensus-shipyard/fendermint/pull/329 that removes the need to build `fendermint` and the docker image as it picks it up from the docker registry.
- It adds an `--hex` flag to `ipc-cli wallet export` to return the hex encoded private key of an address in wallet (expected by the new scripts).
- Updates docs accordingly.

IPC-354: update infra scripts to use FM-329

---

ipc/cli/src/commands/wallet/export.rs

Anyone on the machine can read a created private key—fixed that.

make private keys readable for owners only

---

Makefile

IPC-357: remove the use of unstable flag in make build

---

Cargo.lock
Cargo.toml
ipc/cli/src/commands/crossmsg/fund.rs
ipc/cli/src/commands/crossmsg/mod.rs
ipc/cli/src/commands/crossmsg/release.rs
ipc/cli/src/commands/subnet/join.rs
ipc/cli/src/commands/subnet/mod.rs
ipc/provider/src/lib.rs
ipc/provider/src/manager/evm/manager.rs
ipc/provider/src/manager/subnet.rs

`ipc-cli` implementation for https://github.com/consensus-shipyard/fendermint/issues/347
Depends on: https://github.com/consensus-shipyard/ipc-solidity-actors/pull/267
This PR:
* Adds a flag to include genesis balance for a validator when it joins. 
* Adds a `pre-fund` command for users to be able to add genesis balance in a child subnet before it is bootsrapped.
* It includes the genesis balance information in the `GenesisInfo` call made through the provider so Fendermint can use it to generate its genesis with this initial balance information.
* Adds a `pre-release` command to recover funds from the initial balance of a subnet before it bootstraps.

IPC-347: add pre-fund command and genesis balances in GenesisInfo call

---

Cargo.toml
dev.md
docs/quickstart-calibration.md
docs/usage.md

Closes https://github.com/consensus-shipyard/ipc/pull/new/ipc-363-pre-fund-docs
It also removes outdated stuff from `Cargo.toml` and a pretty old `md` file.

IPC-363: adds docs for pre-fund/pre-release

---

ipc/cli/src/commands/checkpoint/bottomup_height.rs
ipc/cli/src/commands/checkpoint/relayer.rs

Simple fix to accept `0x` as part of the relayer command in `--submitter` such as: 
```
./bin/ipc-cli checkpoint relayer --subnet /r314159/t410ffumhfeppdjixhkxtgagowxkdu77j7xz5aaa52vy --submitter 0x6be1ccf648c74800380d0520d797a170c808b624
```

FIX: accept 0x address as submitter in relayer

---

docs/quickstart-calibration.md
docs/usage.md
ipc/cli/src/commands/checkpoint/mod.rs
ipc/cli/src/commands/crossmsg/mod.rs
ipc/cli/src/commands/crossmsg/topdown_cross.rs
ipc/provider/src/lib.rs
ipc/provider/src/manager/evm/manager.rs
ipc/provider/src/manager/mod.rs
ipc/provider/src/manager/subnet.rs

Closes #364 
- Adds relayer commands. 
- Includes a `cross-msg parent-finality` command to check the latest parent finality committed in a subnet.

IPC-364: relayer docs and parent finality command

---

ipc/provider/src/manager/evm/manager.rs
ipc/provider/src/manager/subnet.rs

We were having some issues in multi-validator deployments because each validator was generating a different genesis, and leading to a different initial state. The source of the non-determinism was the use of a `HashMap` for the initial balances that was causing each validator to have these accounts in their genesis in a different order, so when the init state was being generated in Fendermint, it was causing them to be assigned a different ID address.

FIX: use BTreeMap instead of HashMap in GenesisInfo to remove non-determinism

---

Dockerfile

The previous Dockerfile was 8 months old. I'm guessing was not being used anywhere? If so, here is an updated Dockerfile that builds the cli tool on its own.

Updated docker file to work with new cli

---

README.md
docs/quickstart-calibration.md
ipc/provider/src/config/mod.rs

Adds the Myeclium subnet with remote glif endpoint to both the default config and the readme. This would make the ipc-cli work out of the box and avoid step 3 in the [quickstart](https://app.gitbook.com/o/DdhSSU8GveMWTVvBCegp/s/tw05J6huF10RyduiiqIu/quickstarts/deploy-smart-contracts-to-mycelium#3.-configure-ipc-cli-to-connect-to-the-mycelium-calibration). We could also leave it commented out, but this seems strictly better.
Closes #389 
@trruckerfling We'll need to update the docs once this makes it to main.

Add Mycelium to default config

---

Dockerfile
README.md
docs/quickstart-calibration.md
ipc/cli/src/commands/mod.rs
ipc/cli/src/commands/wallet/import.rs
ipc/provider/src/config/mod.rs
ipc/provider/src/manager/evm/manager.rs
ipc/provider/src/manager/subnet.rs

Propagates last week of changes, including changes to:
* Genesis non-determinism
* Dockerfile
* Log filtering
* Default config
* Help messages
* Docs
The main goal is avoiding stale references to old calibration network. I've been running the dev branch with no issues.

Propagate nov changes to main

---

ipc/cli/src/commands/crossmsg/topdown_cross.rs

List topdown messages in a range with `from` and `to` parameters. This addresses: https://github.com/consensus-shipyard/ipc/issues/358

List topdown messages in range

---

Cargo.lock
ipc/cli/src/commands/subnet/create.rs
ipc/cli/src/lib.rs
ipc/provider/src/lib.rs
ipc/provider/src/manager/evm/manager.rs
ipc/sdk/src/subnet.rs

Depends on: https://github.com/consensus-shipyard/ipc-solidity-actors/pull/305
Upgrades contract version and introduces a `permissioned` flag to address https://github.com/consensus-shipyard/ipc-solidity-actors/issue/304

IPC-304: add permissioned flag for new contract version
