- src/jsonrpc/mod.rs
- src/jsonrpc/tests.rs
- src/lotus/client.rs
- src/lotus/message.rs
- src/lotus/mod.rs
- src/lotus/tests.rs
Add 3 json rpc calls to lotus client:
- state_network_name
- state_network_version 
- state_actor_code_cids
to assist create subnet actors in #28.
> add lotus rpc call

- src/jsonrpc/mod.rs
- src/lotus/client.rs
Fix a doc test compilation error during message migration.
> fix doc tests

- Cargo.toml
- src/cli/commands/daemon.rs
- src/config/mod.rs
- src/config/subnet.rs
- src/server/handlers/create.rs
- src/server/handlers/mod.rs
- src/server/jsonrpc.rs
- src/server/mod.rs
This PR introduces the common trait used for json rpc handler.
Refer to #46 for sample integration with json rpc server.
> add json rpc handler trait

- src/cli/commands/create.rs
- src/cli/commands/daemon.rs
- src/cli/commands/mod.rs
- src/cli/mod.rs
- src/config/mod.rs
- src/config/server.rs
- src/main.rs
- src/server/handlers/create.rs
- src/server/handlers/mod.rs
Create subnet actor command line handler.
This is just a direct json rpc call to ipc agent json rpc server.
Update: Add global config params so that config path will be shared by all cli commands.
> Create subnet cli

- ipld/resolver/src/behaviour/content.rs
Fixes #86 
Followup for #90 
Just realised that if we set the rate limit to zero than `RateLimit::new` will divide by zero. Fixed it.
> IPC-86: Fix rate limiting with 0 to avoid division by zero

- Cargo.lock
- src/lotus/client.rs
- src/lotus/message/ipc.rs
- src/lotus/mod.rs
- src/manager/lotus.rs
- src/server/handlers/validator.rs
Update lotus get subnet actor state to work with lotus node.
> Update lotus api

- src/cli/commands/mod.rs
- src/config/server.rs
- src/lotus/client.rs
- src/lotus/message/ipc.rs
- src/lotus/mod.rs
- src/manager/lotus.rs
- src/manager/mod.rs
- src/manager/subnet.rs
- src/server/handlers/manager/list.rs
- src/server/handlers/manager/list_subnets.rs
- src/server/handlers/manager/mod.rs
- src/server/handlers/mod.rs
List subnets in a gateway actor.
> list subnets

- Cargo.lock
- Cargo.toml
- src/lotus/message/ipc.rs
- src/manager/checkpoint.rs
- src/manager/mod.rs
This PR implements the checkpointing logic where the subnets specified in the config are actively monitored for checkpointing epochs and, for each account that the agent manages in a subnet, a checkpoint is submitted to the subnet actor in the parent subnet. PR #60 is a dependency.
> Implements logic for actively checkpointing the state of managed subnets.

- src/manager/lotus.rs
- src/manager/subnet.rs
Fund and release gateway actor call.
> Fund and release

- src/cli/commands/manager/create.rs
- src/cli/commands/manager/fund.rs
- src/cli/commands/manager/join.rs
- src/cli/commands/manager/kill.rs
- src/cli/commands/manager/list_subnets.rs
- src/cli/commands/manager/mod.rs
- src/cli/commands/manager/propagate.rs
- src/cli/commands/manager/release.rs
- src/cli/commands/manager/whitelist.rs
- src/cli/commands/mod.rs
- src/config/server.rs
- src/server/handlers/manager/fund.rs
- src/server/handlers/manager/mod.rs
- src/server/handlers/manager/propagate.rs
- src/server/handlers/manager/release.rs
- src/server/handlers/manager/whitelist.rs
- src/server/handlers/mod.rs
Add more rpc calls and cli commands for `fund`, `release`, `propagate` and `whitelist`.
> Add more commands

- Cargo.lock
- src/cli/commands/manager/mod.rs
- src/cli/commands/manager/send_value.rs
- src/cli/commands/manager/wallet.rs
- src/cli/commands/mod.rs
- src/config/server.rs
- src/lotus/message/state.rs
- src/manager/lotus.rs
- src/manager/subnet.rs
- src/server/handlers/manager/mod.rs
- src/server/handlers/manager/send_value.rs
- src/server/handlers/manager/wallet.rs
- src/server/handlers/mod.rs
Depends on https://github.com/consensus-shipyard/ipc-agent/pull/121
In the line https://github.com/consensus-shipyard/ipc-agent/pull/121 this PR includes a new command in the agent to create new wallets in a subnet
> Wallet new command

- src/jsonrpc/mod.rs
- src/lotus/client.rs
- src/lotus/message/ipc.rs
- src/lotus/message/mod.rs
- src/lotus/message/serialize.rs
- src/lotus/message/tests.rs
- src/manager/lotus.rs
- src/server/handlers/manager/list_subnets.rs
Fix list subnets parsing error.
> Update list subnet

- src/lotus/client.rs
- src/lotus/json.rs
- src/lotus/message/ipc.rs
- src/lotus/mod.rs
The title is self-descriptive. Depends on #139 and is a dependency of #141
> Adds method IPCGetVotesForCheckpoint to LotusClient

- src/cli/commands/manager/list_checkpoints.rs
- src/cli/commands/manager/mod.rs
- src/cli/commands/mod.rs
- src/config/server.rs
- src/lotus/client.rs
- src/lotus/mod.rs
- src/manager/lotus.rs
- src/manager/subnet.rs
- src/server/handlers/manager/list_checkpoints.rs
- src/server/handlers/manager/mod.rs
- src/server/handlers/mod.rs
Adds a command that lists a range of checkpoints. This is predicated on a Lotus JSON-RPC method for getting a range of checkpoints.
> Adds a list-checkpoints command

- src/lotus/client.rs
- src/lotus/message/ipc.rs
- src/lotus/mod.rs
- src/manager/checkpoint.rs
This PR adapts the logic of bottom-up checkpoint submission to the new actor refactor.
> Adapt bottom-up checkpoints to actor refactor

- src/manager/topdown.rs
When the validator is lagging the current epoch in top down checkpoint submission, we should submit as many as possible the lagging epoches. This is achieved by using a similar `loop` (to bottom up) before sleep.
> Add top down checkpoint submission looping

- src/manager/topdown.rs
Updates:
- Loop submission of top down checkpoints
- Fix state wait in top down checkpoint
- Fix nonce in creating top down messages
> Topdown loop submission

- docs/quickstart.md
- docs/subnet.md
- docs/troubleshooting.md
- docs/usage.md
- src/cli/commands/checkpoint/mod.rs
- src/cli/commands/subnet/create.rs
- src/config/mod.rs
This PR includes some docs for the usage and operation of cross-net messages.
> docs for cross-net messages

- docs/quickstart.md
- docs/subnet.md
Sorry, got pulled into something else and forgot to PR this.
> Replace nohup suggestions

- src/cli/commands/crossmsg/fund.rs
- src/cli/commands/crossmsg/release.rs
- src/lotus/message/state.rs
- src/manager/lotus.rs
- src/manager/subnet.rs
- src/server/handlers/manager/fund.rs
- src/server/handlers/manager/release.rs
This is addressing issue: #177.
> Return chain epoch for fund and release

- src/cli/commands/wallet/import.rs
- src/lotus/message/wallet.rs
> Cli wallet import

- docs/quickstart.md
- docs/subnet.md
- src/cli/commands/mod.rs
- src/cli/commands/wallet/export.rs
- src/cli/commands/wallet/import.rs
- src/cli/commands/wallet/mod.rs
- src/cli/mod.rs
- src/lotus/message/wallet.rs
This PR: 
- Fixes wallet export so it reads from the keystore and uses the right format so it can be imported.
- It updates docs to use ipc-agent identity management.
> fix export and docs

- src/server/handlers/mod.rs
Fix fil parsing to u64 overflown issue so that the correct amount of fil is parsed.
> fix floating point overflown

- testing/itest/examples/no_create_subnet.rs
- testing/itest/examples/no_tear_down.rs
- testing/itest/examples/self_destruct.rs
- testing/itest/src/infra/mod.rs
Updates here and there that are fixes from performing integration testing.
> Updates from Integration testing

- contracts/Gateway.json
- contracts/SubnetActor.json
- src/checkpoint/fevm/bottomup.rs
- src/checkpoint/fevm/topdown.rs
- src/checkpoint/fevm_fvm/bottomup.rs
- src/checkpoint/fevm_fvm/topdown.rs
- src/checkpoint/fvm/bottomup.rs
- src/checkpoint/fvm/topdown.rs
- src/checkpoint/mod.rs
- src/config/subnet.rs
- src/lotus/message/ipc.rs
- src/manager/evm/conversion.rs
- src/manager/evm/manager.rs
- src/manager/evm/mod.rs
- src/manager/lotus.rs
- src/manager/subnet.rs
- src/server/handlers/mod.rs
- src/server/handlers/validator.rs
Support query validator set for EVM. Refactoring the RPC call to use common interface instead of directly calling into lotus.
> Query validator set

- src/manager/evm/manager.rs
Adding `fund` and `release` implementation for evm subnet manager.
> Fund and release implementation

- Cargo.toml
- identity/src/evm/memory.rs
- identity/src/evm/mod.rs
- identity/src/evm/persistent.rs
- identity/src/lib.rs
- src/cli/commands/wallet/import.rs
- src/manager/evm/manager.rs
- src/sdk/wallet.rs
- src/server/handlers/config.rs
- src/server/handlers/manager/create.rs
- src/server/handlers/mod.rs
- src/server/handlers/wallet/import.rs
- testing/itest/src/infra/mod.rs
- testing/itest/src/infra/subnet.rs
- testing/itest/src/infra/util.rs
Add import evm wallet to RPC and cli functions.
> Import evm wallet

- ipc/provider/src/lib.rs
- ipc/provider/src/manager/evm/manager.rs
- ipc/provider/src/manager/subnet.rs
Add more top down finality util queries in provider.
> Support top down query

- Cargo.lock
- ipc/cli/src/commands/crossmsg/release.rs
- ipc/cli/src/commands/subnet/join.rs
- ipc/cli/src/commands/subnet/leave.rs
- ipc/cli/src/commands/subnet/mod.rs
- ipc/provider/src/lib.rs
- ipc/provider/src/lotus/message/ipc.rs
- ipc/provider/src/manager/evm/manager.rs
- ipc/provider/src/manager/subnet.rs
- ipc/sdk/src/cross.rs
- ipc/sdk/src/evm.rs
Updates contract bindings to the latest version in order to include `fee` in cross messages
As part of the update it also addresses some of the tasks in #330
> Fix: update contract bindings

- Cargo.lock
- ipc/provider/src/lib.rs
- ipc/provider/src/manager/evm/manager.rs
- ipc/provider/src/manager/evm/mod.rs
- ipc/provider/src/manager/mod.rs
- ipc/provider/src/manager/subnet.rs
Changes for detecting chain reorgs.
> Detect chain reorg

- Cargo.lock
- Cargo.toml
- README.md
- docs/quickstart-calibration.md
- ipc/cli/src/commands/subnet/create.rs
- ipc/provider/src/config/deserialize.rs
- ipc/provider/src/config/mod.rs
- ipc/provider/src/config/serialize.rs
- ipc/provider/src/config/subnet.rs
- ipc/provider/src/config/tests.rs
- ipc/provider/src/lib.rs
- ipc/provider/src/manager/evm/manager.rs
- ipc/sdk/src/subnet.rs
- ipc/testing/e2e/scripts/connect.sh
Closes https://github.com/consensus-shipyard/ipc-solidity-actors/issues/242
> SOL-242: remove network_name and accounts from config

- Cargo.lock
- ipc/cli/src/commands/checkpoint/mod.rs
- ipc/cli/src/commands/checkpoint/relayer.rs
- ipc/cli/src/commands/mod.rs
- ipc/identity/src/evm/mod.rs
- ipc/provider/src/checkpoint.rs
- ipc/provider/src/manager/evm/manager.rs
- ipc/provider/src/manager/subnet.rs
- ipc/sdk/src/checkpoint.rs
Adding relayer cli plus some small fixes.
> Relayer cli

- ipc/provider/src/lib.rs
Fix getting validator changes error.
> fix validator set error

- ipc/provider/src/manager/evm/manager.rs
Query past validator change set instead of stream.
> Query event instead of stream

- Cargo.lock
- ipc/cli/src/commands/subnet/join.rs
- ipc/cli/src/commands/subnet/mod.rs
- ipc/provider/src/lib.rs
- ipc/provider/src/manager/evm/manager.rs
- ipc/provider/src/manager/subnet.rs
Closes https://github.com/consensus-shipyard/ipc/issues/345
> IPC-345: add unstake command

- Cargo.lock
- Cargo.toml
- ipc/cli/src/commands/checkpoint/list_validator_changes.rs
- ipc/cli/src/commands/checkpoint/mod.rs
- ipc/cli/src/commands/checkpoint/topdow_cross.rs
- ipc/cli/src/commands/subnet/genesis_epoch.rs
- ipc/cli/src/commands/subnet/join.rs
- ipc/cli/src/commands/subnet/list_subnets.rs
- ipc/cli/src/commands/subnet/mod.rs
- ipc/provider/src/lib.rs
- ipc/provider/src/lotus/message/ipc.rs
- ipc/provider/src/lotus/message/tests.rs
- ipc/provider/src/manager/evm/manager.rs
- ipc/provider/src/manager/subnet.rs
- ipc/sdk/src/staking.rs
Adding a lot of util cli commands for debugging and UX.
> More CLI commands

- ipc/cli/src/commands/checkpoint/bottomup_bundles.rs
- ipc/cli/src/commands/checkpoint/bottomup_height.rs
- ipc/cli/src/commands/checkpoint/bottomup_submitted.rs
- ipc/cli/src/commands/checkpoint/mod.rs
- ipc/cli/src/commands/checkpoint/quorum_reached.rs
- ipc/cli/src/commands/checkpoint/relayer.rs
- ipc/provider/src/checkpoint.rs
- ipc/provider/src/lib.rs
- ipc/provider/src/manager/evm/manager.rs
- ipc/provider/src/manager/subnet.rs
- ipc/sdk/src/checkpoint.rs
Query the quorum reached event to trigger processing of checkpoint submission.
> Query event

- docs/quickstart-calibration.md
- ipc/cli/src/commands/subnet/bootstrap.rs
This PR fixes minor bugs that I have found during of testing of the deployment steps within Quickstart Guide.
> Fix minor bugs found during manual testing

- docs/quickstart-calibration.md
This PR fixes several misprints in the quickstart guide.
> Fix misprints in quickstart-calibration.md

- ipc/cli/src/commands/subnet/mod.rs
- ipc/cli/src/commands/subnet/validator.rs
- ipc/provider/src/lib.rs
- ipc/provider/src/manager/evm/manager.rs
- ipc/provider/src/manager/subnet.rs
- ipc/sdk/src/staking.rs
Add method to query validator information.
> add validator info

- ipc/cli/src/commands/wallet/balances.rs
> IPC-373: Fix balances returned with bogus rpc

- ipc/cli/src/commands/subnet/list_subnets.rs
> IPC-366: fix token units in list subnets

- README.md
- docs/quickstart-calibration.md
- ipc/provider/src/config/mod.rs
Update reference to latest M2.5 release contract addresses in Calibration.
> UPDATE: M2.5 contract addresses

- ipc/provider/src/manager/evm/manager.rs
Same as https://github.com/consensus-shipyard/ipc/pull/392
I opened a new PR because changing the base of the PR from `main` to `dev` got stuck.
> Fix filter reverted logsFIX: Filter reverted logs

- ipc/cli/src/commands/mod.rs
- ipc/cli/src/commands/wallet/import.rs
This PR fixes https://github.com/consensus-shipyard/ipc/issues/381
> Fix wallet CLI

- Cargo.lock
- Cargo.toml
- ipc/cli/src/commands/crossmsg/topdown_cross.rs
- ipc/provider/src/manager/evm/manager.rs
- ipc/sdk/src/evm.rs
Query topdown messages through event. This needs to be merged after: https://github.com/consensus-shipyard/ipc-solidity-actors/pull/285
> Topdown query by events

- Cargo.lock
- Cargo.toml
- ipc/provider/src/manager/evm/manager.rs
Uses the new `RegisterDiamondFacet`. 
Depends on https://github.com/consensus-shipyard/ipc-solidity-actors/pull/298
> Fix subnet registry diamond

- ipc/cli/src/commands/mod.rs
- ipc/cli/src/lib.rs
- ipc/cli/src/main.rs
- ipc/provider/src/lib.rs
Use cli parameter: `--network` or `NETWORK` to set the network variable. This addresses: https://github.com/consensus-shipyard/ipc/issues/321
> Use cli parameter to set netowrk

- README.md
- docs/quickstart-calibration.md
- ipc/provider/src/config/mod.rs
Updates Mycelium address following restart on 06/12.
> Update mycelium address
