consensus-shipyard/ipc

ipc/README.md, ipc/docs/quickstart-calibration.md, ipc/ipc/provider/src/config/mod.rs
Pull the changes into the `ipc` subtree.
```
git subtree pull -P ipc        https://github.com/consensus-shipyard/ipc.git dev
```
=> CHORE: Pull ipc

.github/workflows/ci.yaml, .github/workflows/fendermint-publish.yaml
Use https://github.com/dorny/paths-filter to limit when certain jobs are run
=> CI: Only run jobs when files changed

.dockerignore, .github/workflows/ci.yaml, contracts/.gitignore, contracts/Makefile, contracts/binding/build.rs, fendermint/.dockerignore, fendermint/.gitignore, fendermint/Makefile, fendermint/docker/builder.ci.Dockerfile, fendermint/docker/builder.local.Dockerfile, fendermint/docker/runner.Dockerfile
The docker context needs to be the root directory now, so all paths need to change.
=> FIX: Fix paths in docker builds

Cargo.lock, Cargo.toml, contracts/binding/Cargo.toml, fvm-utils/primitives/Cargo.toml, fvm-utils/runtime/Cargo.toml
This PR updates a few sub crates to use workspace dependencies where applicable
=> Update few sub crates to use workspace dependencies

fendermint/README.md
This PR updates the fendermint/README after the monorepo switch
=> fix: update fendermint readme

fendermint/Makefile
=> fix: fendermint Makefile error when running make all

contracts/src/lib/SupplySourceHelper.sol, contracts/src/subnet/SubnetActorManagerFacet.sol
This PR fixes minor issues in the code:
- removing the unnecessary return
- fixing potential reentrancy
=> Fix minor issues

contracts/src/lib/LibSubnetActor.sol
The PR Fixes issue 46: implement check the number of validators before the loop to save gas
=> fix audit-issue-46

contracts/src/lib/priority/LibMaxPQ.sol
The PR fixes audit issue 45: fixing comment
=> fix audit-issue-45

contracts/src/lib/priority/LibMaxPQ.sol
This PR fixes comments and uses bit shift instead of multiplication.
=> Fix audit-issue-42

contracts/README.md
This PR adds some information on how to use audit resolver for NPM.
=> Add guide for npm audit

contracts/test/integration/SubnetActorDiamond.t.sol
This PR adds more tests for the Pausable contract.
=> Add more tests for pauser

fendermint/app/src/cmd/run.rs
Closes #586 
Add subscription and event handling.
=> IPC-586: Subscribe to votes and add them to the tally

contracts/src/lib/LibQuorum.sol
This PR clears the inner mappings properly to avoid any issues.
=> Delete mapping values in LibQuorum

fendermint/vm/interpreter/src/fvm/checkpoint.rs, fendermint/vm/interpreter/src/fvm/state/ipc.rs, ipc/provider/src/checkpoint.rs
Fix the CI error in `create_bottom_up_checkpoint`: perform the gateway enabled check before doing contract queries.
Also fixing a minor issue in  submit checkpoint in relayer.
=> Fix create bottomup checkpoint

contracts/sdk/IpcContract.sol, contracts/src/lib/CrossMsgHelper.sol, contracts/src/lib/LibGateway.sol, contracts/src/structs/CrossNet.sol, contracts/test/sdk/IpcContract.t.sol, contracts/test/unit/CrossMsgHelper.t.sol, contracts/test/unit/LibGateway.t.sol
TODOs snoozed for later: https://github.com/consensus-shipyard/ipc/issues/621
=> add tests for `IpcExchange`.

README.md, docs/ipc/developers.md
After dealing with a complex Cargo dependency issue (see [slack](https://filecoinproject.slack.com/archives/C05J93G9G4F/p1706210700854529?thread_ts=1706174273.058839&cid=C05J93G9G4F)) it makes sense to start a developers guide for common tips where we can concentrate our knowledge
=> Bootstrap developer doc with cargo debugging

fendermint/app/settings/src/lib.rs, fendermint/app/src/cmd/run.rs, fendermint/vm/topdown/src/voting.rs, fendermint/vm/topdown/tests/smt_voting.rs, ipc/api/Cargo.toml, ipc/api/src/subnet_id.rs
Fixes to comments in https://github.com/consensus-shipyard/ipc/pull/600 so we can Squash this and merge that with a Merge Commit if we want.
=> IPC-541: Fix PR comments

contracts/ops/chain-id.sh, contracts/ops/check-rust-binding.sh, contracts/ops/commit-abi.sh, contracts/ops/commit-rust-binding.sh, contracts/ops/compile-abi.sh, contracts/ops/deploy-subnet-registry.sh, contracts/ops/deploy-subnet.sh, contracts/ops/upgrade-gw-diamond.sh, contracts/ops/upgrade-sa-diamond.sh, contracts/ops/upgrade-sr-diamond.sh, contracts/tools/check_aderyn.sh, contracts/tools/check_coverage.sh, infra/fendermint/run.sh
Fixes https://github.com/consensus-shipyard/ipc/issues/663 ENG-651
ensure bash scripts exit whenever a sub process exits or an unused variable is accessed
=>  add set -eu and pipefail in bash scripts

docs/ipc/developers.md
Context: https://filecoinproject.slack.com/archives/C04JR5R1UL8/p1706886901218709
=> docs: Add gotcha in developers.md about local registry crate changes

README.md
=> update ipc-monorepo -> ipc in the Readme

README.md, ipc/provider/src/config/mod.rs
Mycelium has been discontinued for now so it doesn't make sense to confuse the participants of upcoming hackathon
=> Drop Mycelium entries from docs

contracts/audit-resolve.json
=> Resolve npm vulns

fendermint/vm/interpreter/src/fvm/externs.rs
=> fix: do not panic when calling randomness/beacon externs

.github/workflows/auto-deploy-contracts.yaml
This is a leftover item from last PR.
=> Remove trigger on pull request for contract auto deploy workflow

contracts/Makefile, contracts/audit-resolve.json
This PR removes mythril commands from the Makefile
=> Remove mythril targets

fendermint/app/src/main.rs
Related to https://github.com/consensus-shipyard/ipc/pull/755
I noticed while working on https://github.com/consensus-shipyard/ipc/pull/744 that panics during startup do not show up in the log files, only in `docker logs`. If syncing stopped on @maciejwitowski computer (see [Slack](https://filecoinproject.slack.com/archives/C04JR5R1UL8/p1709059894660889)) because it panicked, we would not find it in the logs. This PR should help with that.
=> DEBUG: Log panics so they show up in the log files, not just the console

ipld/resolver/src/behaviour/discovery.rs
See problem report on [Slack](https://filecoinproject.slack.com/archives/C04JR5R1UL8/p1709120541444859):
I'm trying to use kademlia for node discovery.
I set one node as a bootstrap node with
```
FM_RESOLVER__DISCOVERY__STATIC_ADDRESSES=""
```
And all other nodes with
```
FM_RESOLVER__DISCOVERY__STATIC_ADDRESSES="/dns4/fendermint-test-0.service.consul/tcp/27659/p2p/16Uiu2HAm9DLMnvQGuzzo2BTiF21nzAMtYQxXSmqev2zG6PCnsZwC"
```
First node fails to start with
```
2024-02-28T11:41:03.088692Z ERROR fendermint/app/src/main.rs:75: failed to execute Options { home_dir: "/local", log_dir: None, log_file_prefix: None, mode: "dev", log_level: Info, global: GlobalArgs { network: Testnet }, command: Run(RunArgs) }: error creating IPLD Resolver Service
Caused by:
0: Error in the discovery configuration
1: …
```
=> FIX: Do not attempt to bootstrap from self

fendermint/eth/api/src/cache.rs, fendermint/eth/api/src/state.rs
=> Cache address-to-ActorType translation

Makefile, README.md
Default recipe to build `ipc` client from source code
=> make: default recipe

fendermint/app/options/src/config.rs, fendermint/app/options/src/lib.rs, fendermint/app/src/cmd/config.rs, fendermint/app/src/cmd/mod.rs, fendermint/testing/materializer/README.md, fendermint/testing/materializer/src/docker/mod.rs, fendermint/testing/materializer/src/docker/node.rs, fendermint/testing/materializer/src/docker/relayer.rs, fendermint/testing/materializer/src/docker/runner.rs, fendermint/testing/materializer/src/lib.rs, fendermint/testing/materializer/src/logging.rs, fendermint/testing/materializer/src/materializer.rs, fendermint/testing/materializer/src/testnet.rs, fendermint/testing/materializer/src/validation.rs, fendermint/testing/materializer/tests/manifests/layer2.yaml
Builds on https://github.com/consensus-shipyard/ipc/pull/769
Implements `DockerMaterializer::create_relayer`
TODO: 
Deferred:
Set up the same subnet as earlier:
```shell
cargo run -q -p fendermint_app -- \
materializer \
--data-dir $PWD/testing/materializer/tests/docker-materializer-data/ \
setup \
--manifest-file ./testing/materializer/tests/manifests/layer2.yaml
```
Check the relayer logs:
```console
❯ docker logs euston-relayer-aa2681
[2024-03-11T15:22:33Z DEBUG ipc_cli::commands::checkpoint::relayer] start bottom up relayer with args: BottomUpRelayerArgs { subnet: "/r1126193293194756/t410fhwibtof7hp6v5f453q5soyn6ksxym7chbqata2q", checkpoint_interval_sec: None, finalization_blocks: Some(0), submitter: Some("0xba9090181312bd0e40254a3dc29841980dd392d2") }
[2024-03-11T15:22:33Z DEBUG …
```
=> ENG-578: IT (Part 9) - Relayer

fendermint/app/src/app.rs, fendermint/testing/contract-test/src/lib.rs, fendermint/vm/interpreter/src/fvm/state/exec.rs
Adds `FvmExecState::update_base_fee` to make `base_fee` upgradable.
=> ENG-796: Make the base_fee upgradable

fendermint/vm/interpreter/src/fvm/exec.rs
In case the upgrade fails we can skip processing the block anyway.
=> Check for upgrades at beginning of processing a block

fendermint/vm/interpreter/src/chain.rs, fendermint/vm/topdown/src/voting.rs
To help debug the mainnet, adding some more debug logs to help expose the current system.
Might have added more than necessary, will remove some when fully understand the situation.
=> Adding more logs to vote find quorum

.gitignore, extras/linked-token/.prettierignore, extras/linked-token/.prettierrc, extras/linked-token/Makefile, extras/linked-token/package-lock.json, extras/linked-token/package.json, extras/linked-token/script/ConfigManager.sol, extras/linked-token/script/DeployIpcTokenController.s.sol, extras/linked-token/script/DeployIpcTokenReplica.s.sol, extras/linked-token/script/DeployUSDCTest.s.sol, extras/linked-token/src/LinkedToken.sol, extras/linked-token/src/LinkedTokenController.sol, extras/linked-token/src/LinkedTokenReplica.sol, extras/linked-token/test/IpcTokenController.t.sol, extras/linked-token/test/IpcTokenReplica.t.sol, extras/linked-token/test/MultiSubnetTest.t.sol
This uses the same prettier config as for `contracts`.
=> extras/linked-token: add prettier + make fmt.

contracts/src/gateway/GatewayManagerFacet.sol
closes ENG-851
Uses same check code as in fund()
=> Add an early getSubnet() exists check in fundWithToken()

fendermint/rpc/Cargo.toml, fendermint/rpc/src/client.rs, fendermint/rpc/src/query.rs
Help debug some serde parsing issue with gas estimations.
=> DEBUG: Print response on JSON-RPC query errors

specs/materializer.md
Adds documentation about the materializer.
=> Spec: Materializer

specs/ipld-resolver.md
Add docs about the IPLD Resolver.
=> Spec: IPLD Resolver

specs/cometbft.md
=> Spec: CometBFT

contracts/src/errors/IPCErrors.sol, contracts/src/gateway/GatewayBottomUpFacet.sol, contracts/src/gateway/GatewayChildFacet.sol, contracts/src/gateway/GatewayRegistryFacet.sol, contracts/src/gateway/GatewayTopDownFacet.sol, contracts/src/interfaces/IMsgRouting.sol, contracts/src/interfaces/ISubnet.sol, contracts/src/lib/LibMsgExecution.sol, contracts/src/lib/LibUtil.sol, contracts/src/lib/power/LibPower.sol, contracts/src/subnet/FederatedSubnetFacet.sol, contracts/src/subnet/SubnetActorFacet.sol, contracts/src/subnet/SubnetCheckpointingFacet.sol
Migrating topdown message execution to the framework of the contract redesign. The bottom up counter part will be created in a followup PR.
=> Migrating Topdown Message Execution

Cargo.lock, ipc/cli/Cargo.toml, ipc/cli/src/main.rs
bugfix: replace env_logger with tracing_subscriber to enable logging from imported libraries with RUST_LOG env variable
Running an ipc-cli command such as `ipc-cli subnet join --subnet /r314159/t410f3kfub4nv2n6ixbwo37t523upt77l4ezy2altnpy  --collateral 1` with the RUST_LOG variable to trace via `export RUST_LOG=trace` does not enable much logging. This PR changes the logging such that the imported libraries log their information.
Sub issue of ENG-850 but it does not close it. 
Example output with main:
```
mikers@mikers-B560-DS3H-AC-Y1:~/dev/consensus-shipyard/ipc$ ipc-cli subnet join --subnet /r314159/t410f3kfub4nv2n6ixbwo37t523upt77l4ezy2altnpy  --collateral 1 
[2024-05-03T00:06:09Z DEBUG ipc_cli::commands::subnet::join] join subnet with args: JoinSubnetArgs { from: None, subnet: …
```
=> feat(ipc-cli): enable logging from imported libraries

contracts/.gitignore, contracts/package-lock.json, contracts/package.json, contracts/remappings.json, contracts/remappings.txt, contracts/scripts/npm-postpack.js, contracts/scripts/npm-prepack.js, contracts/src/gateway/GatewayManagerFacet.sol, contracts/src/gateway/GatewayMessengerFacet.sol, contracts/src/gateway/router/TopDownFinalityFacet.sol, contracts/src/gateway/router/XnetMessagingFacet.sol, contracts/src/lib/AccountHelper.sol, contracts/src/lib/CrossMsgHelper.sol, contracts/src/lib/LibGateway.sol, contracts/src/lib/LibGatewayActorStorage.sol, contracts/test/IntegrationTestBase.sol, contracts/test/integration/GatewayDiamond.t.sol, contracts/test/integration/GatewayDiamondToken.t.sol, contracts/test/integration/L2GatewayDiamond.t.sol, contracts/test/integration/MultiSubnet.t.sol, contracts/test/integration/SubnetActorDiamond.t.sol, contracts/test/sdk/IpcContract.t.sol, contracts/test/unit/AccountHelper.t.sol
For now we'll do a manual publish to unblock folks, but we'll want to produce automated releases down the line.
=> chore(contracts): prepare for publishing v1.0.0-alpha.0.

specs/supply-sources.md
=> Spec: Supply sources

specs/executions.md
=> docs(specs): Executions

specs/upgrades.md
Added documentation for IPC Upgrades
=> Spec: Upgrades

docs/ipc/usage.md, fendermint/testing/materializer/src/lib.rs, ipc/provider/src/manager/subnet.rs
=> fix: typos

specs/ethapi.md
Add docs about the Ethereum API
=> docs(specs): Ethereum JSON-RPC API

CHANGELOG.md, docs/fendermint/observability.md, specs/drafts/observability.md
=> feat(node): observability docs and changelog section

ipld/resolver/docs/README.md
=> fix: correct link to identify protocol

contracts/binding/src/lib.rs, fendermint/crypto/src/lib.rs, fendermint/vm/topdown/Cargo.toml, fendermint/vm/topdown/src/sync/mod.rs, fendermint/vm/topdown/src/vote/error.rs, fendermint/vm/topdown/src/vote/gossip.rs, fendermint/vm/topdown/src/vote/mod.rs, fendermint/vm/topdown/src/vote/operation/active.rs, fendermint/vm/topdown/src/vote/operation/mod.rs, fendermint/vm/topdown/src/vote/operation/paused.rs, fendermint/vm/topdown/src/vote/payload.rs, fendermint/vm/topdown/src/vote/store.rs, fendermint/vm/topdown/src/vote/tally.rs, fendermint/vm/topdown/tests/vote_reactor.rs
Following previous PR, this one integrates all the vote tally components and handles the reactor.
=> feat(node): vote tally reactor

Cargo.toml
This enables process prometheus metrics.
=> feat: enable process metrics

fendermint/app/src/cmd/run.rs
Closes https://github.com/consensus-shipyard/ipc/issues/1153
=> feat: add `subnet_id` to metrics as a global label

.github/workflows/docker-publish.yaml, fendermint/docker/builder.ci.Dockerfile
=> fix: install target arch

contracts/tasks/deploy-registry.ts
Fix a small issue that misses the deployment of registry diamond.
=> fix: update deploy-registry.ts

README.md
Minor unification of style in the root level README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/consensus-shipyard/ipc/1261)
=> docs(repo): improve root level README.md

ipc/provider/src/checkpoint.rs, ipc/provider/src/manager/evm/manager.rs
Adding more logs from relayer to assist debugging.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/consensus-shipyard/ipc/1306)
=> feat(node): more logs in relayer

Cargo.toml, fendermint/actors/gas_market/eip1559/Cargo.toml, fendermint/app/Cargo.toml, fendermint/app/options/Cargo.toml, fendermint/app/settings/Cargo.toml, fendermint/testing/Cargo.toml, fendermint/testing/contract-test/Cargo.toml, fendermint/vm/actor_interface/Cargo.toml, fendermint/vm/encoding/Cargo.toml, fendermint/vm/genesis/Cargo.toml, fendermint/vm/interpreter/Cargo.toml, fendermint/vm/message/Cargo.toml, fendermint/vm/resolver/Cargo.toml, fendermint/vm/topdown/Cargo.toml, ipc/api/Cargo.toml, ipc/cli/Cargo.toml, ipc/provider/Cargo.toml, ipc/wallet/Cargo.toml, ipld/resolver/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/consensus-shipyard/ipc/1319)
=> fix: reference intra-workspace dependencies by their path

Cargo.lock, Cargo.toml, build-rs-utils/Cargo.toml, build-rs-utils/src/lib.rs, contract-bindings/Cargo.toml, contract-bindings/build.rs, fendermint/actors-builtin-car/Cargo.toml, fendermint/actors-builtin-car/build.rs, fendermint/actors-custom-car/Cargo.toml, fendermint/actors-custom-car/build.rs, fendermint/vm/genesis/Cargo.toml, fendermint/vm/interpreter/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/consensus-shipyard/ipc/1320)
=> feat: convert `build.rs` to custom print macro `echo!`

fendermint/app/settings/src/utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/consensus-shipyard/ipc/1325)
=> fix: simplify `expand_tilde`

contracts/contracts/subnet/SubnetActorManagerFacet.sol
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/consensus-shipyard/ipc/1336)
=> fix: leave subnet and relevant supply account correctly

.gitignore, fendermint/testing/materializer/src/docker/mod.rs, fendermint/testing/materializer/src/docker/node.rs, fendermint/testing/materializer/src/docker/relayer.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/consensus-shipyard/ipc/1347)
=> fix: clippy complaint unused lifetimes

.github/workflows/build.yaml, .github/workflows/tests-e2e.yaml, .github/workflows/tests-unit.yaml, fendermint/app/src/cmd/run.rs, fendermint/rocksdb/src/kvstore.rs, fendermint/storage/src/im.rs, ipc/observability/src/tracing_layers.rs, rust-toolchain.toml
Up the rust version to 1.85.0.
=> feat(node): up rust version

ipc/wallet/src/evm/mod.rs, ipc/wallet/src/evm/persistent.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/consensus-shipyard/ipc/1366)
=> fix: make evm wallets permissioned
