.github/workflows/ipc.yaml, .github/workflows/ipld-resolver.yaml, fendermint/Makefile, ipc/Makefile
Builds the ABI JSON for more `check-clippy` and `ipc` in general.
=> CI: Build ABI for clippy

fendermint/docker/builder.ci.Dockerfile, fendermint/fendermint/testing/src/arb/address.rs, fendermint/fendermint/vm/interpreter/src/fvm/state/ipc.rs, fendermint/fendermint/vm/topdown/src/finality/mod.rs, fendermint/fendermint/vm/topdown/src/finality/null.rs, fvm-utils/primitives/src/uints.rs, ipc/ipc/provider/src/lib.rs
Fixes some new warnings caught after Rust 1.75 became stable.
(Locally I didn't pick them until I ran `rustup update stable`).
=> FIX: New lints with Rust 1.75

fendermint/fendermint/app/src/tmconv.rs, fendermint/fendermint/eth/api/src/apis/eth.rs
Related to #506 
Changes `to_check_tx` to put the error message into `CheckTx::log` instead of `CheckTx::info`, and also fixes `eth::send_raw_transaction` to use `error_with_data` and to make sure the error message propagates through the JSON-RPC pipeline:
```console
$ make deploy-local-ipc
...
Error: 
(code: 2, message: expected sequence 1, got 2, data: Some(String("")))
```
=> FIX: Make sure check errors propagate to JSON-RPC

fendermint/fendermint/vm/actor_interface/src/ipc.rs, fendermint/fendermint/vm/interpreter/src/fvm/genesis.rs, fendermint/fendermint/vm/interpreter/src/fvm/topdown.rs, ipc/ipc/cli/src/commands/crossmsg/fund.rs, ipc/ipc/cli/src/commands/crossmsg/mod.rs, ipc/ipc/provider/src/lib.rs, ipc/ipc/provider/src/manager/evm/manager.rs, ipc/ipc/provider/src/manager/subnet.rs
Implement `fund_with_token` api for erc20 token transfers, see [here](https://github.com/consensus-shipyard/ipc-monorepo/blob/0bae28b402a9bfef072e70048480d22e8d70e59c/contracts/src/gateway/GatewayManagerFacet.sol#L178C14-L178C27).
=> Fund with token

fendermint/fendermint/eth/api/examples/ethers.rs, fendermint/fendermint/eth/api/src/state.rs
Fixes #506 
This is an alternative for #507 that makes 22 exit code work like a `PLACEHOLDER` account by returning `None` from `read_evm_actor`.
I think it's sufficient indication that we're dealing with `ETHACCOUNT`, because:
* `read_evm_actor` is an internal method to the Ethereum API facade, it's only ever called with `H160` addresses and two well known method numbers (`GetCode` and `GetStorageAt`), never with user input
* therefore the `Message` will go to an `f410` address constructed from the 20 byte address hash, and if that exists, it's some sort of Ethereum account or contract (if it didn't exist we wouldn't get code 22)
* if the actor doesn't handle the two well known method numbers, it's not an EVM actor
=> IPC-506: Fix GetCode and GetStorageAt for ethaccount

.github/workflows/fendermint-publish.yaml
After moving to monorepo, we can not use the repository name anymore as the docker image
=> fix: fendermint docker image name

Cargo.lock, Cargo.toml, fendermint/Makefile, fendermint/app/options/src/genesis.rs, fendermint/app/options/src/parse.rs, fendermint/testing/contract-test/tests/staking/state.rs, fendermint/vm/actor_interface/Cargo.toml, fendermint/vm/genesis/src/arb.rs, fendermint/vm/interpreter/src/fvm/externs.rs, ipc/types/Cargo.toml
See: https://github.com/consensus-shipyard/ipc/issues/519
This PR upgrades the FVM to version 4.0.0.
Although the https://github.com/filecoin-project/ref-fvm/pull/1922 feature is not in 4.0.0, it should be easy to add through a tag/branch dependency, will add that in a followup PR.
=> IPC-519: Upgrade to FVM 4.0.0

.github/workflows/ci.yaml
Changes `ci.yaml` to run all Rust workflows if `Cargo.toml` changes, so that if we change some dependency version we don't have to wait until the PR is merged into `master` to see any build failures, which might be only due to `clippy`, as it happened in https://github.com/consensus-shipyard/ipc/pull/569
This is a tradeoff between doing more work with potentially no reason vs fixing stuff on `main`.
=> BUILD: Run tests if Cargo.toml changes

LICENSE-APACHE
The current apache licence is not in canonical form and is not recognised by GH for repo licensing purposes:
This just replaces the text with the standard one.
=> CHORE: Substitute canonical apache licence

fendermint/vm/interpreter/src/chain.rs
Closes #579 
Updates the parent finality in the vote tally whenever a top-down proposal is executed.
=> IPC-579: Update finality in the voting tally

fendermint/app/src/app.rs, fendermint/app/src/tmconv.rs, fendermint/vm/interpreter/src/chain.rs, fendermint/vm/interpreter/src/fvm/exec.rs, fendermint/vm/topdown/src/voting.rs, fendermint/vm/topdown/tests/smt_voting.rs
Closes #578 
Adds a hook to `ChainInterpeter::end` to call a new `VoteTally::update_power_table` if there are changes being passed back to CometBFT in the voting power.
=> IPC-578: Update vote tally power table

fendermint/vm/interpreter/src/chain.rs
Closes #583 
Changes `ChainInterpreter::prepare` so that it looks at both the vote tally and the current parent finality provider: 
1. asks the vote tally if there is a quorum over any height in the parent chain
2. if there is, asks the provider for its next proposal
3. proposes the minimum of the two
This way we go as little as possible forward in the chain: only as much as there is quorum for, but potentially less if some of the existing limits are hit.
This way we don't have to change the logic of the existing provider, we are strictly just gatekeeping it from proposing too early.
=> IPC-583: Use the vote tally in prepare proposal

contracts/src/errors/IPCErrors.sol, contracts/src/subnet/SubnetActorManagerFacet.sol, contracts/test/integration/SubnetActorDiamond.t.sol
This PR fixes ENG-544 and implements the following rule to kill a subnet: a subnet can be killed if it was bootstrapped and does not contains validators.
=> ENG-544: Disallow killing subnet if not bootstrapped

fendermint/eth/api/src/apis/eth.rs
if there is no result for the latest block, we should not decrement the block count. co-authored by @aakoshh
see https://github.com/consensus-shipyard/ipc/pull/602#issuecomment-1903818475
=> eth block count bugfix

contracts/src/lib/LibGateway.sol, contracts/test/integration/GatewayDiamond.t.sol, contracts/test/integration/GatewayDiamondToken.t.sol
Fixing issue #567. 
Adding a "=" to the check, this also forces the tests to advance by some value.
=> Commit parent finality only if finality height is greater

contracts/src/gateway/router/BottomUpRouterFacet.sol
This PR implements the following suggestion from the audit: 
Change the statement to 
```
if (batch.blockHeight % s.bottomUpMsgBatchPeriod != 0 || block.number < batch.blockHeight) {
        revert InvalidBatchEpoch();
}
```
=> ENG-555: Fix check in submitBottomUpMsgBatch

Cargo.lock, fendermint/app/src/tmconv.rs, fendermint/eth/api/Cargo.toml, fendermint/eth/api/src/apis/eth.rs, fendermint/eth/api/src/state.rs, fendermint/rpc/src/client.rs, fendermint/rpc/src/query.rs, fendermint/vm/interpreter/src/fvm/query.rs, fendermint/vm/interpreter/src/fvm/state/query.rs, fendermint/vm/message/src/query.rs
Based on Raul's draft [PR](https://github.com/consensus-shipyard/ipc/pull/514/files) 
Manually verified with
getCode:
* Non existent address: return `0x0`
* EVM account: return `0x0`
* EVM contract: return expected binary code
getStorageAt
* Non existent address: return `0x0`
* EVM account: return `0000000000000000000000000000000000000000000000000000000000000000`
* EVM contract: return expected storage
Integration test covered by existing assertions in `fendermint/eth/api/examples/ethers.rs` running as `smoke-test`.
=> Properly fix eth_getCode and eth_getStorageAt

fendermint/app/config/default.toml, fendermint/app/settings/src/lib.rs, fendermint/app/src/cmd/run.rs, fendermint/vm/topdown/src/voting.rs
Closes ENG-624
Adds a `vote_interval` to the `ipc` settings with a default value of 1 second, which is used to limit the number of top-down finality votes published to gossipsub to maximum 1 per second, to avoid potential bursts. If there are more blocks, it will vote on the latest next time, not the next-in-line height. 
I thought about adding the setting as milliseconds, but stayed with seconds because:
1. all the existing time related values are in seconds
2. I find it unlikely that we can complete more than 1 round of gossip when the block interval is 1 second
3. we only want 1 proposal in a block, so agreeing on one value should suffice
But I could be wrong, maybe the default should be 1000 millis, with an option to set lower values.
=> ENG-624: Vote throttling

fendermint/actors/build.rs
See https://github.com/consensus-shipyard/ipc/issues/643
Issue raised on [slack](https://filecoinproject.slack.com/archives/C04JR5R1UL8/p1706616819780489?thread_ts=1704813449.258009&cid=C04JR5R1UL8)
Before this PR, running the following command took 15-20 seconds as fendermint binary was created every time it ran even though no code changed:
```
cargo run --bin fendermint -- -help
```
Now it should take <1second
=> fix: always compiling fendermint  due to missed directives in build.rs

contracts/ops/deploy.sh
https://linear.app/interplanetary-consensus/issue/ENG-626/ipc-deployment-scripts-fail-instead-of-trying-to-continue-empty
IPC deployment scripts: fail instead of trying to continue empty
This PR should make the deploy script fail when a sub part of it fails. I was able to recreate the early failure using
`export RPC_URL=https://filecoin-calibration.chainup.net/rpc/v1`
```
mikeseiler@Mikes-MacBook-Air contracts % make
./ops/deploy.sh auto
[*] Automatically getting chainID for network
[*] Target network Chain ID: 0x4cb2f
[*] Deploying libraries
[*] Output libraries available in /Users/mikeseiler/dev/consensus-shipyard/ipc/contracts/scripts/libraries.out
[*] Populating deploy-gateway script
[*] Gateway script in /Users/mikeseiler/dev/consensus-shipyard/ipc/contracts/scripts/deploy-gateway.ts …
```
=> add pipefail and unused var error checking on bash script for deploying

contracts/binding/build.rs, contracts/binding/src/lib.rs
Proposal: Lets updated the `build.rs` script to format the `binding/src/lib.rs` file to make sure we don't accidentally format it which causes PR noise/merge conflicts.
=> Keep binding/src/lib.rs codegen file formatted

docs/ipc/quickstart-calibration.md, docs/ipc/usage.md, ipc/cli/src/commands/checkpoint/bottomup_bundles.rs, ipc/cli/src/commands/checkpoint/bottomup_height.rs, ipc/cli/src/commands/checkpoint/list_checkpoints.rs, ipc/cli/src/commands/checkpoint/list_validator_changes.rs, ipc/cli/src/commands/checkpoint/quorum_reached.rs, ipc/cli/src/commands/checkpoint/relayer.rs, ipc/cli/src/commands/crossmsg/fund.rs, ipc/cli/src/commands/crossmsg/propagate.rs, ipc/cli/src/commands/crossmsg/release.rs, ipc/cli/src/commands/crossmsg/topdown_cross.rs, ipc/cli/src/commands/subnet/bootstrap.rs, ipc/cli/src/commands/subnet/create.rs, ipc/cli/src/commands/subnet/genesis_epoch.rs, ipc/cli/src/commands/subnet/join.rs, ipc/cli/src/commands/subnet/kill.rs, ipc/cli/src/commands/subnet/leave.rs, ipc/cli/src/commands/subnet/list_subnets.rs, ipc/cli/src/commands/subnet/rpc.rs, ipc/cli/src/commands/subnet/send_value.rs, ipc/cli/src/commands/subnet/validator.rs, ipc/cli/src/commands/util/f4.rs, ipc/cli/src/commands/wallet/balances.rs, ipc/cli/src/commands/wallet/default.rs, ipc/cli/src/commands/wallet/export.rs, ipc/cli/src/commands/wallet/import.rs, ipc/cli/src/commands/wallet/new.rs, ipc/cli/src/commands/wallet/remove.rs, ipc/cli/src/lib.rs
Issue: https://github.com/consensus-shipyard/ipc/issues/660
Noticed this error when following the quickstart calibration guide. Lets just remove the short names as we should always prefer the long names anyway for clarity
```bash
fridrik@workpc:~/workspace4/ipc-monorepo$ cargo run --bin ipc-cli subnet create --parent /r314159 --min-validators 3 --min-validator-stake 1 --bottomup-check-period 30
Finished dev [unoptimized + debuginfo] target(s) in 0.19s
Running `target/debug/ipc-cli subnet create --parent /r314159 --min-validators 3 --min-validator-stake 1 --bottomup-check-period 30`
thread 'main' panicked at /home/fridrik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.4.14/src/builder/debug_asserts.rs:112:17:
Command create: Short option names must be unique for each …
```
=> Remove short names from all ipc-cli commands

docs/ipc/quickstart-calibration.md
add 
```
alias ipc-cli="cargo run -q -p ipc-cli --release --"
```
to the quickstart-calibration.md
closes ENG-686
preview is here https://github.com/consensus-shipyard/ipc/blob/3eefa2d27aae46c48e4e733b7bfbfd50b8233ccd/docs/ipc/quickstart-calibration.md#step-2-initialise-your-config
=> include alias for ipc-cli shorthand in quickstart calibration docs

contracts/src/gateway/GatewayManagerFacet.sol
=> Disable L3

fendermint/eth/api/src/gas/mod.rs
This PR should address the failing CI clippy task which suddenly started to complain about this. Not sure why as this code hasn't as far as I know changed recently and I don't get this error locally when running `make check-clippy`.
Here is the failing test: https://github.com/consensus-shipyard/ipc/actions/runs/7834028859/job/21376393430?pr=630
=> fix: clippy ptr_arg error on CI

contracts/sdk/IpcContract.sol, contracts/src/errors/IPCErrors.sol, contracts/src/gateway/GatewayGetterFacet.sol, contracts/src/gateway/GatewayManagerFacet.sol, contracts/src/lib/LibGateway.sol, contracts/src/lib/LibStaking.sol, contracts/src/lib/SupplySourceHelper.sol, contracts/src/subnet/SubnetActorCheckpointingFacet.sol
This PR fixes minor findings:
1. Renaming variables and using `revert` for consistency.
2. Adding `nonReentrant` for IPC calls.
3. Checking return value from Set calls.
=> Fix minor findings

ipc/api/src/subnet.rs, ipc/cli/src/commands/subnet/create.rs
https://linear.app/interplanetary-consensus/issue/ENG-613/ipc-cli-avoid-using-int-enum-values-in-arguments
Closes ENG-613
=> [ipc-cli] Use string for argument --supply-source-kind and --permission-mode

ipc/cli/src/commands/wallet/list.rs, ipc/cli/src/commands/wallet/mod.rs
https://linear.app/interplanetary-consensus/issue/ENG-611/ipc-wallet-list-command
Example usage:
```
$ ../target/release/ipc-cli wallet list --wallet-type evm
Address: 0xb4f69b8abc5b3a7f9b085661500b898a29fabe78     PubKey: 045dad983ebf44763387eb8ad65c1f32ea95fc6ac59425862365e13a68e699d4de2f4c4ffb866da7cd3ed56b5a8f7bbcc580107d316d5dc70eefbb33f7f78fdf06
Address: 0xefbd91dcdfd39a7aa2cb6566538ac57c8fe16093     PubKey: 04bdecde198fffcaf8dfc4e98a31ad07b5e653d961eedaba702505c46d749125fe5818a568af1e54de825b581d62734a9adf806e9c32bbbd8ac075af27bce27775
Address: 0xf161ba5e71ea64b34e95a860f3b093425c7ca9af     PubKey: 040e37bd1810d1519b2cf2d8993fe24872f81a81d068252d512cf9be1d0c9918526602423ef53a1523d3ef00658aeeeb1bcdb93942df0696b87b7becf437e1eee9
$ ../target/release/ipc-cli wallet list --wallet-type …
```
=> [ipc-cli] Add ipc wallet list command

.github/workflows/fendermint-publish.yaml, .github/workflows/fendermint-test.yaml
Addresses https://github.com/consensus-shipyard/ipc/issues/685
Pull the latest docker image on CI, which might help with the layer based caching. When I added that caching I forgot that new runners on github won't have the earlier docker registry artifacts at hand.
=> ENG-719: Pull the latest image before building docker

fendermint/eth/api/src/apis/eth.rs
https://filecoinproject.slack.com/archives/C04JR5R1UL8/p1707732077786189?thread_ts=1707502346.036449&cid=C04JR5R1UL8
```
“fuzz: failed to inspect: Database error: failed to get storage for 0xB5022A70376545e134aa89A5EA875F9368a8e667 at 24440054405305269366569402256811496959409073762505157381672968839269610695612: 
Deserialization error: invalid value: string “000000000000000000000000776efa0d1e94ad466838e27c4dfda7cdd1c2bd2d”, expected a 32 byte hex string at line 1 column 66"
```
The string looks like it should parse. Perhaps the client doesn't recognise it as a hex string unless it starts with 0x
=> FIX: Add 0x prefix to eth_getStorageAt response

contracts/src/gateway/GatewayManagerFacet.sol, contracts/src/lib/LibGateway.sol, contracts/test/unit/LibGateway.t.sol, ipc/cli/Cargo.toml, ipc/cli/src/commands/crossmsg/fund.rs
* Reject zero-value token deposits in the gateway.
* Do not revert when unable to create a receipt (see commit message for more details).
* ipc-cli: fund-with-token no longer makes arbitrary assumptions about unit precision.
=> Several fixes related to the token supply source

Cargo.lock, Cargo.toml, ipc/api/Cargo.toml, ipc/api/src/subnet.rs, ipc/cli/Cargo.toml, ipc/cli/src/commands/subnet/create.rs, ipc/provider/Cargo.toml
Follow-up to https://github.com/consensus-shipyard/ipc/pull/684.
This is a bit less pedantic. Ideally we would use clap's [`ValueEnum`](https://docs.rs/clap/latest/clap/trait.ValueEnum.html) going forward, but it's tricky because these types are shared between the cli and the api packages.
=> ipc-cli: use strum for PermissionMode and SupplySourceKind enums.

contracts/test/IntegrationTestBase.sol, contracts/test/sdk/IpcContract.t.sol
Building upon https://github.com/consensus-shipyard/ipc/pull/697 This PR extends beyond the simple refactor of the existing test to add new features.
New tests added:
- add test to `IpcContract.t.sol` to validate `_handleIpcResult` is called when the gateway calls `exch.handleIpcMessage`
=> Expand IpcContract.t.sol to test handleIpcMessage

ipc/cli/src/commands/subnet/list_subnets.rs, ipc/cli/src/commands/subnet/rpc.rs
Closes ENG-639
Please the discussion in linear ticket. Not sure what other subnet commands should adopt this change.
=> Change argument --subnet into --network for some of the ipc-cli subnet commands

ipc/cli/src/commands/subnet/create.rs
Tested
```
$ ./ipc-cli subnet create --parent /r314159 --min-validators 3 --min-validator-stake 1 --bottomup-check-period 30 --supply-source-kind erc20 --supply-source-address 0x0cc94E0b1056Ab7125DD820b406C0A4581CCec91 --permission-mode collateral
[2024-02-16T09:00:18Z INFO  ipc_provider::manager::evm::manager] creating subnet on evm with params: ConstructorParams { min_activation_collateral: 1000000000000000000, min_validators: 3, bottom_up_check_period: 30, ipc_gateway_addr: 0x565ab290180a18b265a5277baf5d8b80a0867991, active_validators_limit: 100, majority_percentage: 60, consensus: 0, power_scale: 3, permission_mode: 0, supply_source: SupplySource { kind: 1, token_address: 0x0cc94e0b1056ab7125dd820b406c0a4581ccec91 }, parent_id: SubnetID { root: 314159, route: [] } } …
```
=> Convert supply source address from eth address to fvm address

fendermint/vm/interpreter/src/fvm/state/ipc.rs
Currently main is broken due to:
```
error[E0412]: cannot find type `XnetMessagingFacetErrors` in module `xnet_messaging_facet`
--> fendermint/vm/interpreter/src/fvm/state/ipc.rs:55:31
|
55 |         xnet_messaging_facet::XnetMessagingFacetErrors,
|                               ^^^^^^^^^^^^^^^^^^^^^^^^ help: a struct with a similar name exists: `XnetMessagingFacet`
|
```
because there are no errors defined in `XnetMessagingFacet`, use `NoRevert` instead.
=> Add no error type

fendermint/eth/api/examples/ethers.rs, fendermint/eth/api/src/conv/from_tm.rs
Fixes https://filecoinproject.slack.com/archives/C04JR5R1UL8/p1708372636330179
Blockscout stopped being able to process logs, with errors such as these:
```json
{
"time": "2024-02-19T19:50:44.490Z",
"severity": "error",
"message": "Task #PID<0.4936.0> started from #PID<0.4911.0> terminating\n** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Log.entry_to_elixir/1\n    (ethereum_jsonrpc 6.1.0) lib/ethereum_jsonrpc/log.ex:165: EthereumJSONRPC.Log.entry_to_elixir({\"logType\", \"event\"})\n    (elixir 1.14.5) lib/enum.ex:1662: anonymous fn/3 in Enum.map/2\n    (stdlib 3.17) maps.erl:410: :maps.fold_1/3\n    (elixir 1.14.5) lib/enum.ex:2480: Enum.map/2\n    (elixir 1.14.5) lib/enum.ex:1552: Enum.into/3\n    (elixir 1.14.5) lib/enum.ex:1658: …
```
=> FIX: Serve empty log_type

contracts/package-lock.json, scripts/deploy_subnet_under_calibration_net/deploy.sh
Last attempt to run failed because submodules had been updated in the repo, but the script didn't update them in working copy: https://github.com/consensus-shipyard/ipc/actions/runs/7973868983
Also update the undici npm dep to pacify npm audit.
=> fix: hosted deployment script: deal with submodules.

scripts/deploy_subnet_under_calibration_net/deploy.sh
This fixes an issue I have with the file `scripts/deploy_subnet_under_calibration_net/deploy.sh` failing on my mac with the error
```
sed: 1: "/CometBFT node ID:/ {n;p}": extra characters at the end of p command
```
The open bsd instance of sed on my mac expects a `;` after the `n;p` part of the sed command
=> bugfix: use a more compatible syntax with bsd sed for mac users

.github/workflows/ci.yaml, .github/workflows/fendermint-publish.yaml
The PR changes `ci.yaml` that previously on ran on `refs/heads/main` to also execute on tagged commits. The tag will become the tag of the docker release. 
So for example if we do `git tag hackathon` and `git push --tags` then it should build and push a `ghcr.io/consensus-shipyard/fendermint:hackathon` image. 
The code previously wanted to strip the `v` prefix from the tag, e.g. ff the tag was like `v1.2.3` then it would have produced `fendermint:1.2.3` image. I commented this out so it becomes `fendermint:v1.2.3`. CometBFT tags also have `v` in them, so I thought why not leave them as-is.
I have done the above actually:
```shell
git checkout docker-push-tagged
git tag hackathon
git push --tagged
```
And it correctly triggered a build on this PR, even though no code changed and the first …
=> BUILD: Enable main-like behaviour on tagged commits

scripts/deploy_subnet_under_calibration_net/deploy.sh
This makes the deploy script more resilient in the edge case that:
1. It's refreshing an existing environment where a local working copy exists.
2. Upstream altered the URLs of submodules.
Thanks to @snissn for suggesting this.
=> fix(scripts/deploy): git submodule sync.

fendermint/vm/event/Cargo.toml
Fixes build warnings caused by duplicate license key _and_ a typo (`worspace`) causing the strum dependency to be malformed.
```
warning: /home/ubuntu/ipc/fendermint/vm/event/Cargo.toml: only one of `license` or `license-file` is necessary
`license` should be used if the package license can be expressed with a standard SPDX expression.
`license-file` should be used if the package uses a non-standard license.
See https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields for more information.
warning: /home/ubuntu/ipc/fendermint/vm/event/Cargo.toml: dependency (strum) specified without providing a local path, Git repository, version, or workspace dependency to use. This will be considered an error in future versions
warning: …
```
=> FIX: vm_event cargo.toml warnings

docs/ipc/contracts.md
contracts.md still referred to ipc-agent and wrong params. There is an inbound link from the [quickstart](https://docs.ipc.space/quickstarts/deploy-a-subnet#step-8-interact-with-your-the-eth-rpc).
I would actually prefer to close this PR and just delete these stale docs. We should no longer have docs in this repo at this stage.
=> Update metamask instructions to use ipc-cli

Cargo.lock, fendermint/eth/api/Cargo.toml, fendermint/eth/api/src/apis/eth.rs, fendermint/eth/api/src/error.rs
Followup for https://github.com/consensus-shipyard/ipc/pull/728
The PR tries to parse the message coming from Solidity `revert` and `require` and attach it to the message returned in the JSON-RPC response, so we don't have to eyeball the hexadecimal output (if there is one) and parse it (how?).
=> ENG-749: Try to parse any revert coming from the EVM as string

fendermint/eth/api/src/state.rs
Ethereum tools like The Graph expect that they can query the _effects_ of the execution of block H at height H. This can lead to problems: for example we deploy a contract at H and it will send an `eth_call` to it at H, but it doesn't exist, because the application state is saved at H+1 to be in line with https://docs.cometbft.com/v0.34/spec/abci/abci#query-1
I did it this way because I think it's important that the CometBFT description of what height to set in queries is respected, even if we don't support proofs based on the state hash. I didn't know what ethereum tools expected, only catered for them by lying about what the latest block height is, so they don't ask for results.
Let's see if the integration tests break.
=> FIX: Adjust query height in the eth api

Cargo.lock, Cargo.toml, fendermint/docker/builder.ci.Dockerfile, ipc/cli/Cargo.toml
Fixes the following error during the multiarch docker build:
```
200.3 error: failed to run custom build command for `openssl-sys v0.9.101`
200.3 
200.3 Caused by:
200.3   process didn't exit successfully: `/app/target/release/build/openssl-sys-48695aebe880d626/build-script-main` (exit status: 101)
200.3   --- stdout
200.3   cargo:rerun-if-env-changed=AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
200.3   AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
200.3   cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
200.3   OPENSSL_LIB_DIR unset
200.3   cargo:rerun-if-env-changed=AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
200.3   AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
200.3   cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
200.3   OPENSSL_INCLUDE_DIR unset
200.3 …
```
=> FIX: ipc-cli OpenSSL problem

.github/workflows/fendermint-test.yaml, fendermint/Makefile, fendermint/testing/materializer/Cargo.toml
Changes the `fendermint-test` workflow to run `make build test` rather than just `make test`, so that we can catch any problems with the build when the tests are not enabled. Hopefully this results in minimal overhead, although that might not be the case if adding the optional features enabled by testing means the artifacts aren't reused. 
With caching tests run as fast as 11 minutes, so let's see how it goes. The `e2e` tests take much longer anyway.
=> CI: Build and test

fendermint/vm/topdown/src/sync/mod.rs, fendermint/vm/topdown/src/sync/syncer.rs
Following the log debug session on [Slack](https://filecoinproject.slack.com/archives/C04JR5R1UL8/p1709136261858299?thread_ts=1709059894.660889&cid=C04JR5R1UL8) I see that [these lines](https://github.com/consensus-shipyard/ipc/blob/3bcef484642775c3c259c603af534708ef3d329f/fendermint/vm/topdown/src/sync/syncer.rs#L191-L217) can take up to 15 minutes to execute. It could be some freakishly slow API calls or (:confounded:) STM live- or deadlocking. 
The PR adds some logging in between these. 
Suspicious logs:
```
"2024-02-27T19:44:01.278908Z", "message":"syncing heights","chain_head":1391238,"pointers":"{tail: {height: 1391199, hash: 9bdf3eae78d33514b3cf262cc16eca91a75845361a906606b660afadbba72390}, head: 1391199}"},"filename":"fendermint/vm/topdown/src/sync/syncer.rs","line_number":96} …
```
=> DEBUG: Add logs between fetch data and caching

fendermint/app/src/app.rs, fendermint/vm/event/src/lib.rs
Adding more events for:
1. Query span
2. Block proposal rejection/acceptance
=> More events for observability

fendermint/app/config/default.toml, fendermint/app/settings/src/lib.rs, fendermint/app/src/cmd/run.rs, fendermint/vm/topdown/src/voting.rs
Adds a new setting to the vote publishing loop that causes the last vote to be re-published after a timeout if there are no new events from the syncer. 
The motivation is to handle a potential situation where the finality cache is saturated with blocks, and therefore they don't trigger new heights to vote on, yet for some reason we aren't finalizing anything new, which means the cache isn't being emptied either. This could potentially happen if somehow everyone has missed the gossip to propose new a new finality to the others.
=> FIX: Re-publish finality vote after a minute

Cargo.lock, Cargo.toml, fendermint/.gitignore, fendermint/app/options/Cargo.toml, fendermint/app/options/src/lib.rs, fendermint/app/options/src/log.rs, fendermint/app/src/main.rs
The PR adds support for more complex log filters to be passed and uses an [EnvFilter](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html) instead of the simple log levels. 
Is it possible to configure log lever of individual components? I want info level overall but want to see debug metrics of kademlia to check if nodes are connected.
Like it is done in cometbft:
```
CMT_LOG_LEVEL  = "main:info,abci-client:debug,*:error"
```
Is this possible with fendermint?
* The default env var we look for is now updated to `FM_LOG_LEVEL`, but `LOG_LEVEL` is still accepted as well. 
* This log level is now applied on the console log, that is, it's no longer restricted to `INFO` level
* Added a separate `FM_LOG_FILE_LEVEL` that governs the filter on the log file. …
=> ENG-770: Accept log filter expressions

fendermint/app/options/src/materializer.rs, fendermint/app/src/cmd/key.rs, fendermint/app/src/cmd/materializer.rs, fendermint/testing/materializer/src/docker/mod.rs, fendermint/testing/materializer/src/materials/defaults.rs
Adds a new command to import an existing secret key to be used in a testnet. 
The use case is that we have already funded via the faucet some keys on Calibration and we want to use them in a test. This PR doesn't implement the skipping of the faucet step, but at least makes it easier to put the keys in the expected places.
```console
❯ cargo run -q -p fendermint_app -- materializer import-key --help
Import an existing secret key into a testnet; for example to use an already funded account on Calibration net
Usage: fendermint materializer import-key --manifest-file <MANIFEST_FILE> --secret-key <SECRET_KEY> --account-id <ACCOUNT_ID>
Options:
-m, --manifest-file <MANIFEST_FILE>
Path to the manifest file.
This is used to determine the testnet ID as well as to check that the account exists. …
```
=> ENG-578: IT (Part 7) - Import secret key into testnet

fendermint/eth/api/src/conv/from_tm.rs, fendermint/eth/api/src/filters.rs, fendermint/eth/api/src/state.rs
See [Slack](https://filecoinproject.slack.com/archives/C05UA7RALFP/p1710027805432869)
```
Mar 09 23:17:37 ip-172-31-40-164 nox[37276]: 2024-03-09T23:17:37.158639Z ERROR tokio-runtime-worker ThreadId(04) chain-listener: newHeads event processing error: newHeads: timestamp field not found; got {"code":23,"message":"failed to process events: Tendermint RPC error: response error\n\nCaused by:\n    Internal error: could not find results for height #1006291 (code: -32603)\n\nLocation:\n    /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10:9 (code: 0)"}
```
We receive this event when we do `eth_subscribe` for `newHeads`:
```
{"code":23,"message":"failed to process events: Tendermint RPC error: response error\n\nCaused by:\n    Internal error: …
```
=> FIX: Add a retry to result fetching in filters

contracts/scripts/util.ts
I think there was a ganache update that lead to our code being out of date. I have upgraded the code that uses ganache to use the new config format. 
Below is an example of how the code works and how you can verify it is working. In the demo below I deploy a gateway using make, edit one of the facets, upgrade the facet, then revert the change locally and upgrade the facet again to the new bytecode.
```
mikers@mikers-B560-DS3H-AC-Y1:~/dev/consensus-shipyard/ipc/contracts$ source .env
mikers@mikers-B560-DS3H-AC-Y1:~/dev/consensus-shipyard/ipc/contracts$ git status
On branch mikers/diamondUpgradeFixes
Your branch is up to date with 'origin/mikers/diamondUpgradeFixes'.
nothing to commit, working tree clean
mikers@mikers-B560-DS3H-AC-Y1:~/dev/consensus-shipyard/ipc/contracts$ git diff …
```
=> Fix Gateway & Registry Diamond Upgrade script

ipc/provider/src/manager/evm/manager.rs
Closes ENG-785.
This PR fixes a bug from calling `ethers` event query. Currently the contract address is not specified, which means other subnets' events can be queried as well or even attackers faking events. This PR solves this issue by fixing the contract address.
=> FIX: filter event by contract

fendermint/eth/api/src/conv/from_tm.rs, fendermint/vm/message/src/conv/from_fvm.rs, fendermint/vm/message/src/signed.rs
Fixes a vulnearability in the signature checking where `message.to` was converted to an Ethereum `H160` address type even if it was an f1 or f2 address. This would have allowed an attacker to alter the recipient address type of the FVM message and send funds to potentially irrecoverable addresses.
The reason it was like this was because originally the method was made for the purpose of displaying FVM transactions in the Ethereum API _somehow_, ie. even if the address was an f2 address, it was happy to show it so the transaction can be browsed.
=> FIX: Reject non-eth message.to if message.from is eth

fendermint/app/options/src/lib.rs, ipc/cli/src/commands/mod.rs, ipc/cli/src/lib.rs
> Also would be awesome so be able to specify ipc config path with env variable
Adds the `IPC_CLI_CONFIG_PATH` env var for the `config.toml` path and an `IPC_NETWORK` as a prefixed version of `NETWORK`. 
Fendermint has `FM_NETWORK` which I admit isn't ideal. I think people would frown on `FM_` prefixes in the `ipc-cli`, so this PR also changes `fendermint` to look for some environment variable aliases, preferring the `FM_` version but also accepting `IPC_` in this case, as well as the non-prefixed version. The same treatment is added to the `FM_LOG_LEVEL`, which allowed me to remove the `_log_level` field; it also looks for `RUST_LOG` now, which is the variable the `ipc-cli` uses (and might be tried based on intuition for those used to Rust libraries).
=> CLI: Add env var for config path

Cargo.lock, fendermint/app/Cargo.toml, fendermint/app/src/events.rs, fendermint/tracing/src/lib.rs
Followup for https://github.com/consensus-shipyard/ipc/pull/796
Adds back the name of the event as `event = <name>` because it turns out that there is [no way to configure](https://github.com/tokio-rs/tracing/blob/908cc432a5994f6e17c8f36e13c217dc40085704/tracing-subscriber/src/fmt/format/mod.rs#L930) the subscriber to display the `name` - which would be useless in other cases anyway as it defaults to filename and line which are already displayed.
=> FIX: emit event name as a field

ipc/cli/src/lib.rs
https://github.com/consensus-shipyard/ipc/pull/787 introduced a bug by not including a `long` name for the hidden network argument, which now captured the _following_ word even if it wasn't present, so it tried to interpret a subcommand as a network. 
In the future, https://github.com/consensus-shipyard/ipc/pull/769 will exercise the `ipc-cli` in CI and catch this kind of bug.
Before:
```console
$ alias ipc-cli="docker run -it --rm -u $(id -u) -v $HOME/.ipc:/fendermint/.ipc fendermint:latest ipc-cli"
$ ipc-cli -- --help
error: invalid value '--help' for '[NETWORK]': expected 0 or 1 for network: invalid digit found in string
```
After:
```console
$ cargo run -q -p ipc-cli -- --help
The IPC agent command line tool
Usage: ipc-cli [OPTIONS] [COMMAND]
...
```
=> FIX: Fix the name of the --network parameter in ipc-cli

fendermint/vm/interpreter/src/fvm/state/exec.rs
https://github.com/consensus-shipyard/ipc/pull/717 added the `app_version` field to `FvmStateParams` but did it as a breaking change. Nodes that already had data in RocksDB are unable to start. 
This fixes it by letting them fill in the default 0 value.
=> FIX: Add default to deserializer for app_version

contracts/src/GatewayDiamond.sol, contracts/src/lib/LibGenesis.sol, contracts/src/lib/LibStaking.sol, contracts/src/lib/LibSubnetActor.sol, contracts/src/lib/LibSubnetActorStorage.sol, contracts/src/structs/Subnet.sol, contracts/src/subnet/SubnetActorGetterFacet.sol, contracts/src/subnet/SubnetActorManagerFacet.sol, contracts/test/helpers/TestUtils.sol, contracts/test/integration/MultiSubnet.t.sol, contracts/test/integration/SubnetActorDiamond.t.sol
Fixing genesis validators not updated when `unstake` and `leave` are called.
Currently in `unstake`, when a validator unstakes all the collateral previuosly staked, then the validator address will not be removed from `genesisValidators`, see [line](https://github.com/consensus-shipyard/ipc/blob/9fe1ee01e85ef430b77aceccc90a934ec947edee/contracts/src/subnet/SubnetActorManagerFacet.sol#L200). The same happens to `leave`.
Note that this PR will fail the CI only when https://github.com/consensus-shipyard/ipc/pull/784 is merged into this branch.
=> Update genesis validator lifecycle

contracts/hardhat.config.ts, ipc/cli/src/commands/subnet/mod.rs, ipc/cli/src/commands/subnet/set_federated_power.rs, ipc/provider/src/lib.rs, ipc/provider/src/manager/evm/manager.rs, ipc/provider/src/manager/subnet.rs
This closes ENG-769
Usage example:
(Against a local ETH net)
```bash
$ ../target/release/ipc-cli subnet set-federated-power --subnet /r31337/t410f6gbdxrbehnaeeo4mrq7wc5hgq6smnefys4qanwi --validator-addresses 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc 0x70997970c51812dc3a010c7d01b50e0d17dc79c8 --validator-pubkeys 048318535b54105d4a7aae60c08fc45f9687181b4fdfc625bd1a753fa7397fed753547f11ca8696646f2f3acb08e31016afac23e630c5d11f59f61fef57b0d2aa5 049d9031e97dd78ff8c15aa86939de9b1e791066a0224e331bc962a2099a7b1f0464b8bbafe1535f2301c72c2cb3535b172da30b02686ab0393d348614f157fbdb 04ba5734d8f7091719471e7f7ed6b9df170dc70cc661ca05e688601ad984f068b0d67351e5f06073092499336ab0839ef8a521afd334e53807205fa2f08eec74f4 --validator-power 10 20 30 --from …
```
=> ENG-769 Add CLI command for setting federated power

Cargo.lock, Cargo.toml, ipc/api/Cargo.toml, ipc/api/src/staking.rs
The IPC API module was missing enum variant StakingOperation#SetFederatedPower. The fallback branch of the u8 to enum ended up representing unrecognized ABI values as SetMetadata operations. Consequently, SetFederatedPower commands were being wrongly translated and applied in the subnet gateway as SetMetadata commands.
Add the missing enum variant and make the conversion typesafe by using try_from. To avoid being pedantic, use num_enum macros. This create was anyway part of the build graph already, so we might as well use it.
Shoutout to @mikevoronov and @folex from Fluence Labs for finding and reporting this!
=> fix: missing enum variant for StakingOperation.

contracts/src/gateway/router/TopDownFinalityFacet.sol
Federated validation is a bit messy right now. There are two phases:
1. Pre-bootstrap and pre-genesis: the sum of collateral and explicit power determine the weight of a validator.
2. Post-bootstrap and post-genesis: only setFederatedPower calls are allowed. Collateral-based [changes are disallowed](https://github.com/consensus-shipyard/ipc/blob/0855f0fd0b267942e3e2e4b3bf5ff8d5fbe0596d/contracts/src/subnet/SubnetActorManagerFacet.sol#L161).
This fixes the weight calculation in the child within phase 2, summing the explicit power to the collateral-based power (fixed at genesis).
Note: This calculation should not happen inside the subnet. See design discussion at https://github.com/consensus-shipyard/ipc/pull/784.
=> fix(federated validation): make subnet gateway use federated power to calculate power table

contracts/src/gateway/router/TopDownFinalityFacet.sol
The weight of a validator does not include the federated power in the child gateway. This is causing the validator's weight to be calculated wrongly in the child. This PR updates the weight to include federated power.
=> [workaround]: count federated power into collateral ignoring `permissionMode`

fendermint/app/options/src/lib.rs
Currently the configuration directory is expected to be under the `--home-dir` (by default `~/.fendermint`) named `config`, with the following content:
* `default.toml` always expected
* `<mode>.toml`  optional, where `<mode>` comes from the [--mode](https://github.com/consensus-shipyard/ipc/blob/7715c04c3ad9b1da4a39f332d0f6080f39db5622/fendermint/app/options/src/lib.rs#L106-L107) CLI option
* `local.toml` also optional
The `default.toml` is copied into the `fendermint` container, and it was expected that operators can _mount_ a custom configuration as a volume under `/fendermint/config/local.toml` for example. However if someone wants to modify the `FM_HOME_DIR` to an empty volume, then it is inconvenient that they have to procure a `default.toml` that has all the right fields. 
This PR …
=> CONFIG: Make the configuration directory configurable

ipc/cli/src/commands/subnet/set_federated_power.rs, ipc/provider/src/manager/evm/manager.rs
We received multiple complaints that `ipc-cli subnet set-federated-power` was invariably failing due to a contract revert. It turns out we were not correctly setting the `from` account as the signer of the transaction.
This PR also applies other minor fixes.
=> fix(cli): set-federated-power: use correct signer middleware.

fendermint/app/settings/src/lib.rs, fendermint/app/src/cmd/run.rs
Exposes the `auth_token` setting of the IPC provider in the fendermint settings.
=> ENG-797: Add parent_http_auth_token to topdown settings

fendermint/actors/eam/src/lib.rs
It is okay to allow contracts to deploy other contracts, they don't need to be whitelisted.
=> EAM: Allow deployments by contracts

contracts/scripts/util.ts
more flexible search for filename in case the typescript files are not generated flatly in the typechain/factories folder
working on https://linear.app/interplanetary-consensus/issue/ENG-801/test-upgradability-of-subnet-actor-and-subnet-registry
I discovered that without any clear indication of what's changed locally on my linux development machine I was failing to find local bytecode.
This PR includes a recursive search through the directory and throws an error if it is not found. 
I can confirm that with this PR, the gateway and subnet registry diamond upgrade scripts are working
=> Fix diamond upgrade failing to find typescript bindings

fendermint/app/config/default.toml, fendermint/app/settings/src/lib.rs, fendermint/app/src/app.rs, fendermint/app/src/cmd/run.rs, fendermint/app/src/lib.rs, fendermint/app/src/main.rs, fendermint/vm/interpreter/src/fvm/upgrades.rs
This PR introduces `halt_height` to the fendermint config which when set (is non zero) will cause fendermint to halt and exit with a unique exit code.
Make sure we have `halt_height` set in our fendermint config (if its not set, you will see a "missing field halt_height" error when starting fendermint). Here we set it to halt at height 450:
```
> cat ~/.fendermint/config/default.toml | grep -B 2 halt_height
halt_height = 450
```
Start fendermint and observe that once it process block height 450 it stops with an exit code of value `2`:
```
> cargo run -p fendermint_app --release -- run
...
2024-03-19T13:57:51.946154Z  INFO fendermint/app/src/app.rs:786: event=NewBlock block_height=448
2024-03-19T13:57:52.904824Z  INFO fendermint/app/src/app.rs:677: event=ProposalProcessed is_accepted=true …
```
=> Add halt_height option to gracefully stop a node at certain height

extras/axelar-token/.env.example, extras/axelar-token/script/Deploy.s.sol, extras/axelar-token/src/IpcTokenHandler.sol, extras/axelar-token/test/TestHandler.sol
1. We introduce the notion of an "admin" address as the recovery operator.
2. We now handle failures when parsing semi-untrusted input, and when invoking the IPC gateway. If any of those fail, we increment the allowance of the admin so they can operate the otherwise locked tokens.
3. When the subnet reports a failure crediting the deposit (e.g. such as if the recipient was a smart contract / actor that reverted), we increment the allowance of the admin also. This is more failsafe and easier to operate than crediting the funds to the recipient on the L1 (who wouldn't be able to rescue them if it was a smart contract, unless it could manage to deploy itself onto the same address it had in the subnet, plausible if it used Deploy3).
4. As an ultimate backstop, we introduce a method so that …
=> extras/axelar-token: improve error handling and add recovery paths.

Cargo.lock, fendermint/actors/eam/Cargo.toml, fendermint/actors/eam/src/lib.rs, fendermint/actors/eam/src/state.rs
- This method allows updating a deployer allowlist.
- It can only be called when the permissioning mode is Allowlist.
- It must be called by a currently authorized deployer.
This method is bound to an FRC42 method number. Its arguments are CBOR-encoded. It can be called from an f1/f3 account by sending a native transaction, or from an f410 account using this path: https://github.com/consensus-shipyard/ipc/pull/773.
=> feat(eam): add `EAM#UpdateDeployers`.

contracts/src/errors/IPCErrors.sol, contracts/src/gateway/router/CheckpointingFacet.sol, contracts/src/subnet/SubnetActorCheckpointingFacet.sol, contracts/test/integration/GatewayDiamond.t.sol, contracts/test/integration/SubnetActorDiamond.t.sol, contracts/test/unit/LibGateway.t.sol
One of the key assumptions for bottom up checkpoint are:
1. Bottom up checkpoints are submitted at a fixed interval, i.e. multiples of bottom up checkpoint period
2. Bottom up checkpoint heights are sequential, say the checkpoint period is 10, then heights are 10, 20, 30, ...
With the message batch mechanism, one is allowed to submit at an earlier checkpoint height, e.g. if the last checkpoint height is 10 and the message batch is full at height 12, then bottom up checkpoint submission is allowed at height 12. However, when the above happens, the next expected checkpoint height is not specified clearly. At the same time, past checkpoints are allowed to be submitted but no opt is done (for historically reason). For example, past checkpoints are allowed …
=> Tighten next bottom up checkpoint height

fendermint/rpc/examples/transfer.rs, fendermint/testing/smoke-test/Makefile.toml, fendermint/vm/interpreter/src/signed.rs, fendermint/vm/message/src/signed.rs
This change changes the signature checks to allow the case where an ethereum account wants to send a message to a non-ethereum account, e.g. to fund an `f1` account from an `f410` account, where the `f410` address was funded on the subnet by the `ipc-cli`.
So far this has not been allowed because if `message.from` was an ethereum address then the method number had to be `evm::Method::InvokeContract`, which didn't work with custom actors (although an `Account` would have been able to receive funds this way), but due to the vulnearability fixed in https://github.com/consensus-shipyard/ipc/pull/772 a message sent from the EthAPI can only go to an Ethereum account, so f1 wasn't allowed (or, should not have been allowed). 
The solution on Filecoin is …
=> SIG: Allow eth to send to non-eth with regular signature

fendermint/docker/docker-entry.sh
Previously when we run `ipc-cli` with a docker image, the terminal won't react to Ctrl-C. This PR fixes it.
Closes ENG-778
Local test result
```bash
$ docker run -it -v ~/.ipc:/fendermint/.ipc fendermint:latest ipc-cli checkpoint relayer --subnet /r314159/t410fw3df6gtwycgozfolgfqrwagd3p5yn53uf34ptgi --submitter 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
[2024-03-24T20:24:13Z INFO  ipc_provider::checkpoint] launching bottom-up relayer, parent: /r314159, child: /r314159/t410fw3df6gtwycgozfolgfqrwagd3p5yn53uf34ptgi for t410f6op5nzi2vwepn5gonk4ie4tzz773sitggxp4hiy
[2024-03-24T20:24:13Z INFO  ipc_provider::checkpoint] last submission height: 1440
(...push ctrl-c)
^C[1]    57887 exit 130   docker run -it -v ~/.ipc:/fendermint/.ipc fendermint:latest ipc-cli checkpoin
```
=> React to Ctrl-C when running ipc-cli using a docker image

infra/fendermint/Makefile.toml, infra/fendermint/scripts/subnet.toml
Otherwise `[[` is not recognized by sh.
=> Add shebang in tasks.subnet-genesis-set-eam-permissions script

ipc/cli/src/commands/checkpoint/relayer.rs, ipc/provider/src/checkpoint.rs
This closes ENG-767.
We now support submitting bottum-up checkpoint with limited parallelism, configured by `--max-parallel-submission` flag in `ipc-cli checkpoint relayer` command.
=> Support submit checkpoint in parallel

fendermint/app/config/default.toml, fendermint/app/config/test.toml, fendermint/app/settings/src/lib.rs, fendermint/app/settings/src/resolver.rs, fendermint/app/src/cmd/run.rs, ipld/resolver/src/service.rs, ipld/resolver/tests/smoke.rs
I was under the impression that the `libp2p::Swarm` somehow gets the external [address reported](https://github.com/libp2p/rust-libp2p/blob/1a9cf4f7760724032b729c43165716c7ecd842ad/swarm/src/lib.rs#L1193) to it and it passes it on [to Kademlia](https://github.com/libp2p/rust-libp2p/blob/695404d56bf51cd86d983e3c699d71bdbd9e87d1/protocols/kad/src/behaviour.rs#L2621) but it doesn't seem to work with more involved network setups. 
This PR adds a `FM_RESOLVER__CONNECTION__EXTERNAL_ADDRESSES` setting which accepts a list of `Multiaddr` types.
=> CONFIG: Add setting for external addresses for the resolver

fendermint/app/settings/src/lib.rs, fendermint/app/src/cmd/run.rs, fendermint/vm/topdown/src/finality/null.rs, fendermint/vm/topdown/src/lib.rs
Expose max_cache_block in fendermint so that one can set this paremter. Also adding a few extra parameters in logging proposals.
=> Expose max_cache_block parameter for parent syncing

fendermint/testing/graph-test/Makefile.toml, fendermint/testing/graph-test/subgraph/package.json
Our build has started failing due to this deprecated use of `docker-compose`. Probably some builder image changed to exclude `docker-compose`.
=> fix(ci): docker-compose is deprecated; switch to docker compose.

contracts/src/gateway/GatewayManagerFacet.sol, contracts/src/lib/SupplySourceHelper.sol, contracts/test/IntegrationTestBase.sol, contracts/test/helpers/ERC20Deflationary.sol, contracts/test/helpers/ERC20Inflationary.sol, contracts/test/helpers/ERC20Nil.sol, contracts/test/integration/MultiSubnet.t.sol
closes ENG-713
NOTE the suggested behavior on the previous item was to skip the top down message, but instead this PR executes a revert. This seemed to be the more appropriate behavior from my perspective on best practices. LMK if i am missing something and will remove the revert and skip the top down message in the gateway
See [this thread](https://filecoinproject.slack.com/archives/C065VJDDSJH/p1711370060434969) for a doubt I am checking with Zokyo.
Add tests for these scenarios:
=> fundToken Inflation / Deflation / Tax on transfer Fix

fendermint/eth/api/src/apis/eth.rs, fendermint/eth/api/src/cache.rs, fendermint/eth/api/src/conv/from_eth.rs, fendermint/eth/api/src/conv/from_tm.rs, fendermint/eth/api/src/lib.rs, fendermint/eth/api/src/mpool.rs, fendermint/eth/api/src/state.rs, fendermint/testing/materializer/src/materials/defaults.rs, fendermint/testing/materializer/src/testnet.rs, fendermint/testing/materializer/tests/docker_tests/mod.rs, fendermint/testing/materializer/tests/docker_tests/standalone.rs, fendermint/testing/materializer/tests/manifests/standalone.yaml
The PR enhances the `ethapi` to be able to cache ~and buffer~ transactions until they are included in the blockchain, so that it can deal with ~out-of-order submissions and~ plug the gap in the API where an Ethereum transaction is submitted, but it's not found by its hash until it's executed and indexed by its _domain hash_ by CometBFT. 
Deferred to future PRs:
```bash
cargo test -p fendermint_materializer --test docker -- mempool --nocapture
```
=> ENG-731: Cache transactions in the ethapi

Cargo.lock, fendermint/app/options/src/debug.rs, fendermint/app/options/src/genesis.rs, fendermint/app/options/src/lib.rs, fendermint/app/src/cmd/debug.rs, fendermint/app/src/cmd/genesis.rs, fendermint/app/src/cmd/mod.rs, fendermint/vm/topdown/src/sync/mod.rs, fendermint/vm/topdown/src/sync/syncer.rs, ipc/api/src/staking.rs, ipc/provider/Cargo.toml, ipc/provider/src/checkpoint.rs, ipc/provider/src/jsonrpc/mod.rs, ipc/provider/src/lib.rs, ipc/provider/src/lotus/client.rs, ipc/provider/src/lotus/message/state.rs, ipc/provider/src/manager/evm/manager.rs
Adds a CLI command to fetch topdown events of a subnet and export them to JSON. These could be read into an upgrade and applied on the child subnet.
As an alternative, one can use the Filfox API: https://filfox.info/api/v1/address/f410fqpww4v74jydq25jncdbletyqd42oxyeoapzaz4a/events?page=0&pageSize=5
```console
❯ cargo run -q -p fendermint_app -- debug ipc export-top-down-events --help
Fetch topdown events from the parent and export them to JSON.
This can be used to construct an upgrade to impute missing events.
Usage: fendermint debug ipc export-top-down-events [OPTIONS] --subnet-id <SUBNET_ID> --parent-endpoint <PARENT_ENDPOINT> --start-block-height <START_BLOCK_HEIGHT> --end-block-height <END_BLOCK_HEIGHT> --events-file <EVENTS_FILE>
Options:
-s, --subnet-id <SUBNET_ID>
Child subnet for …
```
=> ENG-842: Export topdown events

scripts/add_license.sh
Recently Macos switched to BSD grep which does not have the -P option.
Running for example `make lint` on Macos resulted in making changes to all source files since it thought they had missing header which can take a while to fix when you have other local changes.
Example:
```
10:53@Fridriks-MBP ~/workspace/ipc-monorepo$ make lint
./scripts/add_license.sh
grep: invalid option -- P
usage: grep [-abcdDEFGHhIiJLlMmnOopqRSsUVvwXxZz] [-A num] [-B num] [-C[num]]
[-e pattern] [-f file] [--binary-files=value] [--color=when]
[--context[=num]] [--directories=action] [--label] [--line-buffered]
[--null] [pattern] [file ...]
fendermint/abci/examples/kvstore.rs was missing header
grep: invalid option -- P
usage: grep [-abcdDEFGHhIiJLlMmnOopqRSsUVvwXxZz] [-A num] [-B num] [-C[num]]
[-e pattern] [-f …
```
=> Fix add_licence script on mac

Cargo.lock, ipc/cli/src/commands/subnet/join.rs, ipc/provider/Cargo.toml, ipc/provider/src/lib.rs
fixes issue brought up by @fridrik01 regarding the "from" argument being optional. 
code was moved from ipc/cli/src/commands/subnet/join.rs to ipc/provider/src/lib.rs and looks cleaner
=> ipc-cli subnet join to extract pubkey from the wallet -- From argument fixes 

Cargo.lock, Cargo.toml, fendermint/abci/examples/kvstore.rs, fendermint/abci/src/application.rs, fendermint/app/Cargo.toml, fendermint/app/config/default.toml, fendermint/app/settings/src/lib.rs, fendermint/app/src/cmd/run.rs, fendermint/vm/interpreter/src/bytes.rs
Adds a `tower` service layer that limits the concurrent requests going to the `consensus` connection to 1, which should hopefully solve the issue of transactions being applied in a different order than they appear in the block. This is the actual fix for a [problem we had with end_block](https://github.com/consensus-shipyard/ipc/commit/4b2c90b2cf053c85d6ff684e4ae7d6b228c31eb9). 
A buffer is added so that the other channels aren't blocked while `consensus` isn't ready. See [here](https://docs.rs/tower/latest/tower/struct.ServiceBuilder.html#order) for example. 
To be honest I don't understand this - this limit only affects the `Connection`, but a single `Connection` instance effectively only serves one kind of request, because CometBFT opens 4 different sockets to the service. By the looks …
=> ENG-854: Limit consensus concurrency to 1

Cargo.lock, docs/ipc/usage.md, fendermint/testing/materializer/src/docker/mod.rs, ipc/cli/src/commands/subnet/join.rs, ipc/provider/Cargo.toml, ipc/provider/src/lib.rs, scripts/deploy_subnet_under_calibration_net/deploy.sh
This closes ENG-612. I am still gaining Rust experience, but this did seem straight forward enough. I copied the code from 
cli/src/commands/wallet/export.rs:125 into JoinSubnet to calculate the public key.
working:
```
mikers@mikers-B560-DS3H-AC-Y1:~/dev/consensus-shipyard/ipc/ipc$ ipc-cli subnet create --parent /r314159 --min-validator-stake 1 --min-validators 1 --bottomup-check-period 5 --supply-source-kind native  --
from 0x1c6c6494ee7c390c81352f218ba698a065ba4feb --permission-mode collateral
[2024-04-09T23:55:05Z INFO  ipc_provider::manager::evm::manager] creating subnet on evm with params: ConstructorParams { min_activation_collateral: 1000000000000000000, min_validators: 1, bottom_up_check_
period: 5, ipc_gateway_addr: 0xb4271dc950665e8598cef7d0c7eb3efc44e064f2, …
```
=> ipc-cli subnet join to extract pubkey from the wallet

contracts/package-lock.json
fixes ENG-861
running `check-audit --omit dev --audit-level critical fix` created the update
=> fix npm audit - upgrade dep

contracts/src/lib/SubnetIDHelper.sol, contracts/test/helpers/FvmAddressHelper.sol, contracts/tools/check_aderyn.sh
Fixes ENG-860
Fixes three errors found by Aderyn checker among two types of error: encodePacked and Unprotected initializer
**Error**:
files : `contracts/src/lib/SubnetIDHelper.sol` and `contracts/test/helpers/FvmAddressHelper.sol`
error message: `Found high vulnerability: abi.encodePacked() should not be used with dynamic types when passing the result to a hash function such as keccak256()` 
**Solution**: 
changed abi.encodePacked to string.concat 
**Error**:
`src/lib/LibDiamond.sol`
`Unprotected initializer at src/lib/LibDiamond.sol line 204`
**Solution**: 
Modify the bash script contracts/tools/check_aderyn.sh that allow lists specific filename, error name and line number tuples. 
```
IGNORE_SPECIFIC["src/lib/LibDiamond.sol:203:Unprotected initializer"]=1 …
```
=> fix aderyn false positives

fendermint/rocksdb/src/kvstore.rs, fendermint/storage/src/im.rs, fendermint/storage/src/lib.rs, fendermint/storage/src/testing.rs
Adds an `iterate` method to the `KVRead` abstraction if the `KVStore::Repr` type implements `Ord`. 
It could be extended to take a parameter like the RocksDB implementation to say whether we want to iterate from the start, the end, from a specific key, or in between two keys; perhaps `iterate` could take parameters and a `KVCollection::iter` could just do the default in-order one. Here I just wanted to see how it can be implemented and where to add it.
This is a support PR for https://github.com/consensus-shipyard/ipc/pull/914 to implement initialisation from the storage.
=> STORAGE: KVRead::iterate

fendermint/testing/graph-test/Makefile.toml, fendermint/testing/graph-test/subgraph/graph-node/docker-compose.yaml
Fixes the issues that I've run into trying to run the e2e tests on my new Macbook. 
I was getting errors running `make e2e` under the `fendermint` directory. 
[] Specify `amd/64` platform to Docker when pulling the go-ipfs and graph-node images
[] Unix `sleep 30` instead of GNU `sleep 30s` (without specifying a unit, it will default to seconds anyways)
=> Fixes E2E tests on Apple Silicon

.github/workflows/contracts-prettier.yaml, .github/workflows/contracts-test.yaml, contracts/sdk/IpcContractUpgradeable.sol
[__Ownable_init()](https://github.com/consensus-shipyard/ipc/blob/b6d472d41601af6327df9c98dd0c486f57c77eaf/contracts/sdk/IpcContractUpgradeable.sol#L32) function requires `msg.sender` param in [@openzeppelin/contracts-upgradeable v5](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/f960f47267044822613be18e149c2e0ee1a3bf6e/contracts/access/OwnableUpgradeable.sol#L51)
=> fix(contracts/sdk): `IpcUpgradableOwnable`: pass `msg.sender` to `Ownable` `init` for compatibility with OZ v5

specs/customizability.md
Added documentation for IPC Customazbility
=> docs(specs): Customizability

fendermint/Makefile, ipc/Makefile
1 of 2 PRs requested in a convo with @raulk. This simply adds `--locked` everywhere possible. I can't remember exactly why I added these on our fork, but some minor dependency bump caused a test failure.
=> Add more cargo --locked to Makefiles

.gitignore, docs-gitbook/SUMMARY.md, docs-gitbook/overview/how-ipc-compares.md, docs-gitbook/overview/how-it-works.md
This pull request aims to enhance the existing documentation by introducing a new section on how it works and updating the benefits overview to provide clearer and more comprehensive information to the users. The changes include:
Addition of a new section covering how IPC works, detailing its purpose and usage.
Updates to the benefits overview, highlighting the key advantages and improvements of the current system.
These improvements are intended to make the documentation more user-friendly and informative, aiding users in better understanding and utilizing the features of our product.
=> Enhance Documentation: Add New Section on how it works and update current docs

fendermint/eth/api/src/apis/eth.rs, fendermint/eth/api/src/apis/mod.rs, fendermint/eth/api/src/apis/net.rs, fendermint/eth/api/src/apis/web3.rs
Normalizes all methods to carry 2 arguments. Methods not requiring parameters accept a Params type with an empty tuple generic type.
---
Yeah, this kinda bites the bullet you didn't wanna bite @karlem. But it results in cleaner code overall.
=> consolidate macros for measuring Eth request latency.

specs/drafts/observability.md
**View the [rendered](https://github.com/consensus-shipyard/ipc/blob/raulk/spec-observability/specs/drafts/observability.md) version.**
This PR introduces a spec to improve and evolve our observability features. The spec details:
- Our mental model.
- A list of events we seek to capture, including the traces and metrics they result in.
- A new journal abstraction for trace object logging, inspired by Lotus' (which I happened to design/implement 😆).
- A simplified implementation approach.
=> specs: introduce a new observability model

Cargo.lock, fendermint/app/options/Cargo.toml, fendermint/app/options/src/lib.rs, fendermint/app/options/src/log.rs, fendermint/app/src/main.rs, fendermint/app/src/metrics/prometheus.rs, fendermint/app/src/metrics/tracing.rs, fendermint/vm/topdown/src/observe.rs, ipc/observability/src/lib.rs, ipc/observability/src/traces.rs, ipc/observability/src/tracing_layers.rs
Close #1057 
There is a problem with using the configuration file because we want to set up tracing before the configuration is loaded. At least, this is how it currently works. Therefore, some kind of dynamic layer will need to be added to the subscriber layer when we want to use the configuration file. That is why I just used environment variables for now to cut corners and get this out as soon as possible. Once all metrics are implemented, I can fix the configuration reloading.
=> Introduce New Observability - Configuration

.github/workflows/contracts-sast.yaml, contracts/foundry.toml, contracts/tools/check_aderyn.sh
Root cause:
1. pnpm hoists dependencies to the workspace root and uses symlinks to link them under `node_modules`.
2. Aderyn performs local compilation calling solc directly.
3. Solc requires the target of symlinks to be whitelisted in `--allow-paths`.
Unfortunately:
1. Aderyn doesn't support passing in allowed paths, nor does it pick them up from Foundry config.
2. I wasn't able to mimic a standard `node_modules` layout with pnpm, after trying various hoisting and linking settings.
So we bite the bullet and perform an ordinary npm install to make Aderyn happy.
Also rewrote the `check_aderyn.sh` script to make it POSIX compliant, so I could run it on macOS to verify the fix.
=> fix(ci): aderyn target.

.github/workflows/lint-pr.yaml
Adds a GitHub workflow that runs on PR events to validate that the PR title matches the conventional commits spec. We use this to generate changelogs with [git cliff](https://git-cliff.org/). This is just a first version, we can iterate on the scopes and types as needed.
=> ci: validate PR titles against conventional commits.

Cargo.lock, Cargo.toml, fendermint/rocksdb/Cargo.toml, fendermint/vm/actor_interface/Cargo.toml, ipc/observability/Cargo.toml, ipc/types/Cargo.toml
The build is failing after Rust 1.80.0 was released (and we adopted it) due to this: https://github.com/time-rs/time/issues/693 Upgrading to the latest minor version of the crate fixes it.
Also fixes a build warning in ipc-observability.
=> chore(deps): upgrade cargo deps.

Cargo.lock, Cargo.toml
The dircpy has a bug which was fixed in a higher version, but the cargo update ran previously used the buggy version. This pr fixes it and fix the crate version.
=> fix: fix dircpy crate bug

.github/workflows/contracts-sast.yaml, .github/workflows/lint-pr.yaml
It's cute that someone once thought this was the thing to prioritise instead of actually writing more thoughtful docs.
=> chore(ci): remove codespell.

contracts/.prettierrc, contracts/hardhat.config.ts, contracts/scripts/deploy-gateway.template.ts, contracts/scripts/deploy-libraries.ts, contracts/scripts/deploy-registry.template.ts, contracts/scripts/deploy-sa-diamond.ts, contracts/scripts/js/diamond.js, contracts/scripts/upgrade-gw-diamond.ts, contracts/scripts/upgrade-sa-diamond.ts, contracts/scripts/upgrade-sr-diamond.ts, contracts/scripts/util.ts
We are not in the 80s, we have screens with bigger resolutions now.
=> chore(contracts): set prettier formatting to printWidth=120.

ipc/observability/src/config.rs, ipc/observability/src/traces.rs
The observability caused us to regress by setting the default level to trace. This also cleans up type conversion logic.
=> fix(core): set the default log level to INFO.

contracts/contracts/subnet/SubnetActorManagerFacet.sol
I was reading the function comments when I noticed this.
=> fix: update word spelling

contracts/contracts/errors/IPCErrors.sol, contracts/contracts/lib/AssetHelper.sol, contracts/contracts/lib/LibStaking.sol, contracts/contracts/lib/LibSubnetActor.sol
=> feat(node): address review comments against #1130

spec/bottom up interraction.md
The bottom up interaction spec.
=> Spec: Bottom up interaction

ipc/observability/src/config.rs, ipc/observability/src/lib.rs, ipc/observability/src/traces.rs, ipc/observability/src/tracing_layers.rs
=> feat(node): separate tracing and logging files

docs/fendermint/observability.md, fendermint/app/settings/src/lib.rs, ipc/observability/src/config.rs
- Allow passing `domain_filter` and `events_filter` via env
- Allow passing lowercase log level, e.g., "info", instead of "Info"
=> fix: tracing deserialization

ipc/cli/src/commands/subnet/validator.rs
Our users are tripping over this papercut, so let's add support for both address formats, even though in reality we only support Eth addresses.
=> fix(cli): subnet get-validator: add support for 0x Eth addrs.

ipc/cli/src/commands/util/eth.rs, ipc/cli/src/commands/util/f4.rs, ipc/cli/src/commands/util/mod.rs
This is useful when you need to get the eth contract address from a subnet ID to do, for example, a token approval from a token collateral erc20 contract to the subnet actor contract.
=> feat: ipc cli util command to convert f4 to eth address

contracts/sdk/IpcContractUpgradeable.sol, ipc/observability/src/config.rs, ipc/observability/src/traces.rs
This allows for more flexible log filters like `info,fendermint=debug`.
This also includes a small solhint fix to get `make lint` to work for me locally. My compiler uses solidity `0.8.26`.
=> refactor: replace LogLevel type with String

docs/fendermint/observability.md, fendermint/app/config/test.toml, fendermint/app/src/cmd/run.rs, specs/drafts/observability.md
=> feat: prefix metrics with "ipc"

scripts/deploy_subnet_under_calibration_net/deploy.sh
**Description:**  
This PR updates the deploy command in the `deploy.sh` script under the calibration net deployment process. Specifically, the command was changed from `make deploy-ipc` to `make deploy-stack` to ensure proper contract deployment on the calibration network.
**Changes:**
- Updated `deploy.sh` script to use the correct `deploy-stack` command for calibration net.
**Testing:**  
The change was tested locally and confirmed to deploy the contracts correctly on the calibration network.
=> fix: update deploy command for calibration net

ipc/api/src/lib.rs
Fix a human readable serialisation error from testing new topdown checkpointing. I think I have fixed this before in one of the PRs, but somehow the commit is lost.
Basically the fix is about when Human Readable serialiser is used, it should be doing a check instead of using string serialisation all the way.
=> fix: fix HumanReadable serialization error

contracts/README.md, docs/ipc/deploying-hierarchy.md
Following up on the previous fix in [PR #1184](https://github.com/consensus-shipyard/ipc/pull/1184) — aligning documentation with these changes.
=> fix: docs for deploy command

.github/workflows/contracts-deployment-test.yaml, contracts/tasks/deploy-registry.ts, contracts/tasks/lib/deployments.ts, pnpm-lock.yaml
- **Problem:** The error arises because the nonce, which uniquely identifies each transaction from the sender, is reused while deploying multiple contracts on the calibrationnet. This issue does not occur on a local node, likely because transactions are processed immediately in a single-node environment.
- **Cause:** On a public testnet like calibrationnet, network latency, transaction propagation time, and node synchronization can lead to situations where a new transaction is sent before the previous one is fully confirmed, resulting in nonce reuse.
- **Local Node Success:** On a local node, deployments succeed because transactions are mined instantly, preventing any nonce conflicts.
The solution is to manage the nonce automatically by calling getTransactionCount with the pending …
=> fix: for "Nonce Has Already Been Used" Issue During Deployment on Calibrationnet

docs/fendermint/running.md
Small fix for specifying the `--artifacts-path` flag needed for `seal-genesis` command. 
Without it, the command fails with the following output: 
```
2024-11-12T08:55:38.110971Z ERROR fendermint/app/src/main.rs:45: failed to execute Options { home_dir: "~/.fendermint", config_dir: None, mode: "dev", global: GlobalArgs { network: Testnet }, command: Genesis(GenesisArgs { genesis_file: "test-network/genesis.json", command: Ipc { command: SealGenesis(SealGenesisArgs { builtin_actors_path: "fendermint/builtin-actors/output/bundle.car", custom_actors_path: "fendermint/actors/output/custom_actors_bundle.car", artifacts_path: None, output_path: "test-network/sealed.car" }) } }) }: ipc enabled but artifacts path not provided
=> fix: add `--artifacts-path` flag documentation

fendermint/app/src/cmd/run.rs, fendermint/vm/interpreter/src/fvm/checkpoint.rs, fendermint/vm/interpreter/src/fvm/mod.rs, fendermint/vm/interpreter/src/fvm/observe.rs
Closes https://github.com/consensus-shipyard/ipc/issues/1190
I used address instead of the public key hex encoding. Can change that if wanted.
=> fix: metrics validator label to use address instead of pk struct formatting

Cargo.lock, Cargo.toml, fendermint/Makefile, fendermint/testing/graph-test/Makefile.toml
* `fvm`: "v4.1.0" -> "v4.4.0" 
* `builtin-actors`: "v12.0.0" -> "v15.0.0" 
* `frc42_dispatch` dep version to pin [latest commit](https://github.com/filecoin-project/actors-utils/commit/0f8365151f44785f7bead4e5500258fd5c8944e6) which wasn't tagged or published to crates.io. This is needed for `fvm "v4.4.0"` compatibility. 
* e2e tests to properly apply `${PROFILE}` env var. Otherwise, binaries are built for multiple targets.
=> chore: upgrade `fvm` and `builtin-actors` versions

infra/fendermint/scripts/ethapi.toml
Fixing a bug in infra script that causes ethapi and fendermint to be on different network config.
=> fix: fix inconsistent network btw eth and fendermint

fendermint/eth/api/src/apis/eth.rs
This PR addresses https://github.com/consensus-shipyard/ipc/issues/1225.
This PR updates the matching of query addresses against txn from and to to only user signed txns. IPC message does not really need to check that because it's obviously system call.
=> fix: patch missing ipc messages in eth get_logs

fendermint/app/src/app.rs
Close #1233 
The issue has been resolved by using the current execution state instead of the previous state retrieved through the read-only view. This ensures that the validators cache accurately reflects the latest set of validators, preventing the panic.
=> fix: use current exec state when querying validator table

.github/workflows/auto-deploy-contracts.yaml
This fixes our GitHub Actions workflow to auto-deploy contracts to Calibnet when changes are detected. This has been failing for some months and we never got around to fixing it. New users kept tripping up regularly when following the quickstart tutorial @ docs.ipc.space, which instructs them to deploy their subnet against the existing framework contracts on Calibnet. However, those contracts were outdated leading to severe compatibility issues.
While fixing this, I also:
- Simplified the setup by removing the need for a PAT.
- Removed the merge from main, as GH rejected pushes containing modified workflow files.
- Introduce a cache for incremental compilation and deployment (leveraging hardhat-deploy's ability to skip deployment when a contract with the same bytecode already exists).
- …
=> fix: contracts auto-deploy GitHub Actions workflow

contracts/contracts/errors/IPCErrors.sol, contracts/contracts/gateway/GatewayMessengerFacet.sol, contracts/contracts/interfaces/ISubnetActor.sol, contracts/contracts/lib/AssetHelper.sol, contracts/contracts/lib/CrossMsgHelper.sol, contracts/contracts/lib/LibGateway.sol, contracts/test/integration/GatewayDiamondToken.t.sol, contracts/test/integration/L2PlusXNet.t.sol, contracts/test/unit/CrossMsgHelper.t.sol, contracts/test/unit/LibGateway.t.sol
This PR adds test cases to support L2 plus value. At the same time, fixing a few bugs in previous implementations.
=> feat(node): support l2 value tests

contracts/contracts/errors/IPCErrors.sol, contracts/contracts/gateway/GatewayMessengerFacet.sol, contracts/contracts/interfaces/ISubnetActor.sol, contracts/contracts/lib/AssetHelper.sol, contracts/contracts/lib/CrossMsgHelper.sol, contracts/contracts/lib/LibGateway.sol, contracts/test/integration/GatewayDiamondToken.t.sol, contracts/test/integration/L2PlusSubnet.t.sol, contracts/test/integration/L2PlusXNet.t.sol, contracts/test/integration/MultiSubnet.t.sol, contracts/test/unit/CrossMsgHelper.t.sol, contracts/test/unit/LibGateway.t.sol
This PR builds on previous PR but instead enables the value transfer in cross network messages. 
Update 27/12/24:
- If the message is topdown, lock the value from the supply source of the NEXT child subnet: https://github.com/consensus-shipyard/ipc/pull/1240/files#diff-71559bfe927afaf1a3980c01ffe9f4d15c77d58650b2d850bbae821de9c009d0R76
- Fix postbox key index issue: https://github.com/consensus-shipyard/ipc/pull/1240/files#diff-b26838f2cc5f8bf764313ca069618747d9171766dc768ece47de2d9c38ffddfbR699
- A simple test framework to simulate xnet message flow: https://github.com/consensus-shipyard/ipc/pull/1240/files#diff-53695b3660cd8c2d5418a61e61a1abda1cd2ba05dcc0f607ddd3251b9cc8f57dR466
=> feat(node): support l2 plus value transfer

.github/workflows/build.yaml, .github/workflows/tests-e2e.yaml, .github/workflows/tests-unit.yaml
Currently CI is auto using latest ubuntu, which is now 24.04. This version of ubuntu is using glibc 2.39 and causing the debian image to fail as it only supports 2.36. This PR mainly downgrade ubuntu to 22.04 so that the image can be built correctly.
At the same time, fixing the rust toolchain to align with that specified in `toolchain.toml`. Currently if we up the rust version to 1.84.0, some updated crates requires glibc 2.39, such as:
Also fixing the CI to have the same rust version as toolchain also makes the environments aligned.
=> fix(node): set rust toolchain/job runner to a fix value

contracts/contracts/gateway/GatewayManagerFacet.sol, contracts/contracts/gateway/GatewayMessengerFacet.sol, contracts/contracts/lib/LibGateway.sol, contracts/contracts/lib/LibSubnetActor.sol, contracts/contracts/subnet/SubnetActorManagerFacet.sol, contracts/test/integration/SubnetActorDiamond.t.sol
This PR addresses the review audits.
**Mediums:**
**Lows:**
**Informationals:**
=> fix(contracts): fix contract audit findings

Cargo.toml, ipld/resolver/src/behaviour/mod.rs, ipld/resolver/src/service.rs
During a previous migration, the connection limits were disabled, this re-introduces them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/consensus-shipyard/ipc/1271)
=> feat(node): add connection limits

.github/workflows/ci.yaml, .github/workflows/commonmark-lint.yaml, .github/workflows/lint-pr.yaml, Makefile
All our documentation is in markdown format, but it's not linted for consistency. This PR adds `markdownlint-cli2` checks per PR, to replicated locally a `Makefile` rule was added.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/consensus-shipyard/ipc/1270)
=> docs: add markdown linter

fendermint/testing/materializer/src/arb.rs, fendermint/testing/materializer/src/docker/mod.rs, fendermint/testing/materializer/src/docker/node.rs, fendermint/testing/materializer/src/manifest.rs, fendermint/testing/materializer/src/materializer.rs, fendermint/testing/materializer/src/testnet.rs, fendermint/testing/materializer/tests/manifests/layer2.yaml, fendermint/testing/materializer/tests/manifests/test.toml
Support dynamically loading the Fendermint configuration in Materialier without rebuilding the image. This will significantly improve the testing feedback loop.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/consensus-shipyard/ipc/1286)
=> feat: support dynamic Fendermint config loading in Materializer

contracts/ops/compile-abi.sh
Remove `--via-ir` hardcoding in compile contract abi, so that one can control this parameter in `hardhat.config.ts`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/consensus-shipyard/ipc/1314)
=> fix(node): remove hardcoding in compile abi

Cargo.lock, fendermint/actors-custom-car/Cargo.toml, fendermint/actors-custom-car/build.rs
Currently we use `cargo` as provided by the build env, but this doesn't seem to be the same version as previously, so we now do 2 things:
* use the version as prefix for out
* ensure we use the `channel = ` as defined in `rust-toolchain.toml` (assumes it exists)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/consensus-shipyard/ipc/1322)
=> fix: use `rust-toolchain` defined channel for `wasm` compilation

README.md, docs-gitbook/quickstarts/deploy-a-subnet.md
Hey! We've noticed Node/npm isn't mentioned as a dependency of the project, and it's used to install pnpm and manage contract dependencies (#1020). This adds links for installation to the README and the quickstart gitbook page.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/consensus-shipyard/ipc/1292)
=> docs: add node.js as a prerequisite

ipc/provider/src/checkpoint.rs
Ensure checkpoints are submitted in order, not in parallel, also adds a generous timeout
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/consensus-shipyard/ipc/1345)
=> feat: ordererd submission

contracts/contracts/gateway/router/CheckpointingFacet.sol, contracts/test/integration/GatewayDiamond.t.sol
It is reported that `pruneBottomUpCheckpoints` is never used, removing it.
=> fix: remove pruneBottomUpCheckpoints

.gitmodules, contracts/contracts/lib/AssetHelper.sol, contracts/test/invariants/SubnetRegistryInvariants.t.sol, demos/axelar-token/foundry.toml, demos/linked-token/foundry.toml
This PR adds `ExcessivelySafeCall` to limit the amount of bytes that will be loaded to memory. The gas however is forwarded fully.
=> fix: add ExcessivelySafeCall

contracts/contracts/errors/IPCErrors.sol, contracts/contracts/subnet/SubnetActorCheckpointingFacet.sol, contracts/test/helpers/TestUtils.sol, contracts/test/integration/GatewayDiamond.t.sol, contracts/test/integration/SubnetActorDiamond.t.sol, fendermint/testing/contract-test/tests/staking/machine.rs, ipc/provider/src/checkpoint.rs
Currently submit bottom up checkpoint does not check for duplicated bottom up signers. This exposes multiple security risks. Solidity does not have a gas efficient way of doing sorting or in memory hashmap. The approach is to enforce the signer addresses to be sorted in ascending order. This way we can easily enforce no duplication.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/consensus-shipyard/ipc/1338)
=> fix: submit bottom up checkpoint performs signature check

contracts/contracts/gateway/GatewayManagerFacet.sol, contracts/contracts/lib/AssetHelper.sol
Check the return value of the fund transfer. If it fails, the call should revert.
=> fix: check return value from transfer funds

contracts/contracts/gateway/router/CheckpointingFacet.sol, contracts/test/integration/GatewayDiamond.t.sol
Prevent xnet call messages with non-zero value from inflating child subnet circulating supply
=> fix: prevent xnet call messages with non-zero value from inflating child subnet circulating supply

contracts/contracts/errors/IPCErrors.sol, contracts/contracts/subnet/SubnetActorManagerFacet.sol
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/consensus-shipyard/ipc/1340)
=> fix: gensis validator power

fendermint/docker/builder.ci.Dockerfile, fendermint/docker/builder.local.Dockerfile
… errors
Must be kept in sync with `rust-toolchain.toml`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/consensus-shipyard/ipc/1385)
=> fix: use rust `1.83.0` and avoid artifact version mismatches and fixes `docker-build` target
